// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: education.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyRequest) Reset() {
	*x = GetCompanyRequest{}
	mi := &file_education_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyRequest) ProtoMessage() {}

func (x *GetCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyRequest.ProtoReflect.Descriptor instead.
func (*GetCompanyRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{0}
}

func (x *GetCompanyRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *GetCompanyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCompanyResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title              string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	AvatarUrl          string                 `protobuf:"bytes,3,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
	StartTime          string                 `protobuf:"bytes,4,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime            string                 `protobuf:"bytes,5,opt,name=endTime,proto3" json:"endTime,omitempty"`
	CompanyPhone       string                 `protobuf:"bytes,6,opt,name=companyPhone,proto3" json:"companyPhone,omitempty"`
	Subdomain          string                 `protobuf:"bytes,7,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	ValidDate          string                 `protobuf:"bytes,8,opt,name=valid_date,json=validDate,proto3" json:"valid_date,omitempty"`
	Tariff             *Tariff                `protobuf:"bytes,9,opt,name=tariff,proto3" json:"tariff,omitempty"`
	DiscountId         string                 `protobuf:"bytes,10,opt,name=discount_id,json=discountId,proto3" json:"discount_id,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsDemo             bool                   `protobuf:"varint,12,opt,name=is_demo,json=isDemo,proto3" json:"is_demo,omitempty"`
	ActiveStudentCount int32                  `protobuf:"varint,13,opt,name=active_student_count,json=activeStudentCount,proto3" json:"active_student_count,omitempty"`
	CeoId              string                 `protobuf:"bytes,14,opt,name=ceo_id,json=ceoId,proto3" json:"ceo_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetCompanyResponse) Reset() {
	*x = GetCompanyResponse{}
	mi := &file_education_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyResponse) ProtoMessage() {}

func (x *GetCompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyResponse.ProtoReflect.Descriptor instead.
func (*GetCompanyResponse) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{1}
}

func (x *GetCompanyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCompanyResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetCompanyResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *GetCompanyResponse) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *GetCompanyResponse) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *GetCompanyResponse) GetCompanyPhone() string {
	if x != nil {
		return x.CompanyPhone
	}
	return ""
}

func (x *GetCompanyResponse) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

func (x *GetCompanyResponse) GetValidDate() string {
	if x != nil {
		return x.ValidDate
	}
	return ""
}

func (x *GetCompanyResponse) GetTariff() *Tariff {
	if x != nil {
		return x.Tariff
	}
	return nil
}

func (x *GetCompanyResponse) GetDiscountId() string {
	if x != nil {
		return x.DiscountId
	}
	return ""
}

func (x *GetCompanyResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetCompanyResponse) GetIsDemo() bool {
	if x != nil {
		return x.IsDemo
	}
	return false
}

func (x *GetCompanyResponse) GetActiveStudentCount() int32 {
	if x != nil {
		return x.ActiveStudentCount
	}
	return 0
}

func (x *GetCompanyResponse) GetCeoId() string {
	if x != nil {
		return x.CeoId
	}
	return ""
}

type Tariff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StudentCount  int32                  `protobuf:"varint,3,opt,name=student_count,json=studentCount,proto3" json:"student_count,omitempty"`
	Sum           float32                `protobuf:"fixed32,4,opt,name=sum,proto3" json:"sum,omitempty"`
	Discounts     string                 `protobuf:"bytes,5,opt,name=discounts,proto3" json:"discounts,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,6,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tariff) Reset() {
	*x = Tariff{}
	mi := &file_education_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tariff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tariff) ProtoMessage() {}

func (x *Tariff) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tariff.ProtoReflect.Descriptor instead.
func (*Tariff) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{2}
}

func (x *Tariff) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tariff) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tariff) GetStudentCount() int32 {
	if x != nil {
		return x.StudentCount
	}
	return 0
}

func (x *Tariff) GetSum() float32 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *Tariff) GetDiscounts() string {
	if x != nil {
		return x.Discounts
	}
	return ""
}

func (x *Tariff) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *Tariff) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetGroupsByTeacherIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeacherId     string                 `protobuf:"bytes,1,opt,name=teacherId,proto3" json:"teacherId,omitempty"`
	IsArchived    bool                   `protobuf:"varint,2,opt,name=isArchived,proto3" json:"isArchived,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsByTeacherIdRequest) Reset() {
	*x = GetGroupsByTeacherIdRequest{}
	mi := &file_education_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsByTeacherIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsByTeacherIdRequest) ProtoMessage() {}

func (x *GetGroupsByTeacherIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsByTeacherIdRequest.ProtoReflect.Descriptor instead.
func (*GetGroupsByTeacherIdRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{3}
}

func (x *GetGroupsByTeacherIdRequest) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *GetGroupsByTeacherIdRequest) GetIsArchived() bool {
	if x != nil {
		return x.IsArchived
	}
	return false
}

type GetGroupsByTeacherResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Groups        []*GetGroupByTeacherAbs `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsByTeacherResponse) Reset() {
	*x = GetGroupsByTeacherResponse{}
	mi := &file_education_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsByTeacherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsByTeacherResponse) ProtoMessage() {}

func (x *GetGroupsByTeacherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsByTeacherResponse.ProtoReflect.Descriptor instead.
func (*GetGroupsByTeacherResponse) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{4}
}

func (x *GetGroupsByTeacherResponse) GetGroups() []*GetGroupByTeacherAbs {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GetGroupByTeacherAbs struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,10,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CourseName         string                 `protobuf:"bytes,2,opt,name=courseName,proto3" json:"courseName,omitempty"`
	RoomName           string                 `protobuf:"bytes,3,opt,name=roomName,proto3" json:"roomName,omitempty"`
	LessonStartTime    string                 `protobuf:"bytes,4,opt,name=lessonStartTime,proto3" json:"lessonStartTime,omitempty"`
	DayType            string                 `protobuf:"bytes,5,opt,name=dayType,proto3" json:"dayType,omitempty"`
	GroupStartAt       string                 `protobuf:"bytes,6,opt,name=groupStartAt,proto3" json:"groupStartAt,omitempty"`
	GroupEndAt         string                 `protobuf:"bytes,7,opt,name=groupEndAt,proto3" json:"groupEndAt,omitempty"`
	ActiveStudentCount int32                  `protobuf:"varint,8,opt,name=activeStudentCount,proto3" json:"activeStudentCount,omitempty"`
	Students           []*AbsStudent          `protobuf:"bytes,9,rep,name=students,proto3" json:"students,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetGroupByTeacherAbs) Reset() {
	*x = GetGroupByTeacherAbs{}
	mi := &file_education_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupByTeacherAbs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupByTeacherAbs) ProtoMessage() {}

func (x *GetGroupByTeacherAbs) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupByTeacherAbs.ProtoReflect.Descriptor instead.
func (*GetGroupByTeacherAbs) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{5}
}

func (x *GetGroupByTeacherAbs) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetGroupByTeacherAbs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetGroupByTeacherAbs) GetCourseName() string {
	if x != nil {
		return x.CourseName
	}
	return ""
}

func (x *GetGroupByTeacherAbs) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *GetGroupByTeacherAbs) GetLessonStartTime() string {
	if x != nil {
		return x.LessonStartTime
	}
	return ""
}

func (x *GetGroupByTeacherAbs) GetDayType() string {
	if x != nil {
		return x.DayType
	}
	return ""
}

func (x *GetGroupByTeacherAbs) GetGroupStartAt() string {
	if x != nil {
		return x.GroupStartAt
	}
	return ""
}

func (x *GetGroupByTeacherAbs) GetGroupEndAt() string {
	if x != nil {
		return x.GroupEndAt
	}
	return ""
}

func (x *GetGroupByTeacherAbs) GetActiveStudentCount() int32 {
	if x != nil {
		return x.ActiveStudentCount
	}
	return 0
}

func (x *GetGroupByTeacherAbs) GetStudents() []*AbsStudent {
	if x != nil {
		return x.Students
	}
	return nil
}

type AbsStudent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbsStudent) Reset() {
	*x = AbsStudent{}
	mi := &file_education_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsStudent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsStudent) ProtoMessage() {}

func (x *AbsStudent) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsStudent.ProtoReflect.Descriptor instead.
func (*AbsStudent) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{6}
}

func (x *AbsStudent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AbsStudent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AbsStudent) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

var File_education_proto protoreflect.FileDescriptor

const file_education_proto_rawDesc = "" +
	"\n" +
	"\x0feducation.proto\x12\teducation\";\n" +
	"\x11GetCompanyRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\xbe\x03\n" +
	"\x12GetCompanyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1c\n" +
	"\tavatarUrl\x18\x03 \x01(\tR\tavatarUrl\x12\x1c\n" +
	"\tstartTime\x18\x04 \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\x05 \x01(\tR\aendTime\x12\"\n" +
	"\fcompanyPhone\x18\x06 \x01(\tR\fcompanyPhone\x12\x1c\n" +
	"\tsubdomain\x18\a \x01(\tR\tsubdomain\x12\x1d\n" +
	"\n" +
	"valid_date\x18\b \x01(\tR\tvalidDate\x12)\n" +
	"\x06tariff\x18\t \x01(\v2\x11.education.TariffR\x06tariff\x12\x1f\n" +
	"\vdiscount_id\x18\n" +
	" \x01(\tR\n" +
	"discountId\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x17\n" +
	"\ais_demo\x18\f \x01(\bR\x06isDemo\x120\n" +
	"\x14active_student_count\x18\r \x01(\x05R\x12activeStudentCount\x12\x15\n" +
	"\x06ceo_id\x18\x0e \x01(\tR\x05ceoId\"\xbf\x01\n" +
	"\x06Tariff\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rstudent_count\x18\x03 \x01(\x05R\fstudentCount\x12\x10\n" +
	"\x03sum\x18\x04 \x01(\x02R\x03sum\x12\x1c\n" +
	"\tdiscounts\x18\x05 \x01(\tR\tdiscounts\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x06 \x01(\bR\tisDeleted\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"[\n" +
	"\x1bGetGroupsByTeacherIdRequest\x12\x1c\n" +
	"\tteacherId\x18\x01 \x01(\tR\tteacherId\x12\x1e\n" +
	"\n" +
	"isArchived\x18\x02 \x01(\bR\n" +
	"isArchived\"U\n" +
	"\x1aGetGroupsByTeacherResponse\x127\n" +
	"\x06groups\x18\x01 \x03(\v2\x1f.education.GetGroupByTeacherAbsR\x06groups\"\xe1\x02\n" +
	"\x14GetGroupByTeacherAbs\x12\x0e\n" +
	"\x02id\x18\n" +
	" \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"courseName\x18\x02 \x01(\tR\n" +
	"courseName\x12\x1a\n" +
	"\broomName\x18\x03 \x01(\tR\broomName\x12(\n" +
	"\x0flessonStartTime\x18\x04 \x01(\tR\x0flessonStartTime\x12\x18\n" +
	"\adayType\x18\x05 \x01(\tR\adayType\x12\"\n" +
	"\fgroupStartAt\x18\x06 \x01(\tR\fgroupStartAt\x12\x1e\n" +
	"\n" +
	"groupEndAt\x18\a \x01(\tR\n" +
	"groupEndAt\x12.\n" +
	"\x12activeStudentCount\x18\b \x01(\x05R\x12activeStudentCount\x121\n" +
	"\bstudents\x18\t \x03(\v2\x15.education.AbsStudentR\bstudents\"R\n" +
	"\n" +
	"AbsStudent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vphoneNumber\x18\x03 \x01(\tR\vphoneNumber2u\n" +
	"\fGroupService\x12e\n" +
	"\x14GetGroupsByTeacherId\x12&.education.GetGroupsByTeacherIdRequest\x1a%.education.GetGroupsByTeacherResponse2f\n" +
	"\x0eCompanyService\x12T\n" +
	"\x15GetCompanyBySubdomain\x12\x1c.education.GetCompanyRequest\x1a\x1d.education.GetCompanyResponseB\n" +
	"Z\bproto/pbb\x06proto3"

var (
	file_education_proto_rawDescOnce sync.Once
	file_education_proto_rawDescData []byte
)

func file_education_proto_rawDescGZIP() []byte {
	file_education_proto_rawDescOnce.Do(func() {
		file_education_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_education_proto_rawDesc), len(file_education_proto_rawDesc)))
	})
	return file_education_proto_rawDescData
}

var file_education_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_education_proto_goTypes = []any{
	(*GetCompanyRequest)(nil),           // 0: education.GetCompanyRequest
	(*GetCompanyResponse)(nil),          // 1: education.GetCompanyResponse
	(*Tariff)(nil),                      // 2: education.Tariff
	(*GetGroupsByTeacherIdRequest)(nil), // 3: education.GetGroupsByTeacherIdRequest
	(*GetGroupsByTeacherResponse)(nil),  // 4: education.GetGroupsByTeacherResponse
	(*GetGroupByTeacherAbs)(nil),        // 5: education.GetGroupByTeacherAbs
	(*AbsStudent)(nil),                  // 6: education.AbsStudent
}
var file_education_proto_depIdxs = []int32{
	2, // 0: education.GetCompanyResponse.tariff:type_name -> education.Tariff
	5, // 1: education.GetGroupsByTeacherResponse.groups:type_name -> education.GetGroupByTeacherAbs
	6, // 2: education.GetGroupByTeacherAbs.students:type_name -> education.AbsStudent
	3, // 3: education.GroupService.GetGroupsByTeacherId:input_type -> education.GetGroupsByTeacherIdRequest
	0, // 4: education.CompanyService.GetCompanyBySubdomain:input_type -> education.GetCompanyRequest
	4, // 5: education.GroupService.GetGroupsByTeacherId:output_type -> education.GetGroupsByTeacherResponse
	1, // 6: education.CompanyService.GetCompanyBySubdomain:output_type -> education.GetCompanyResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_education_proto_init() }
func file_education_proto_init() {
	if File_education_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_education_proto_rawDesc), len(file_education_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_education_proto_goTypes,
		DependencyIndexes: file_education_proto_depIdxs,
		MessageInfos:      file_education_proto_msgTypes,
	}.Build()
	File_education_proto = out.File
	file_education_proto_goTypes = nil
	file_education_proto_depIdxs = nil
}
