// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserByCompanyIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByCompanyIdRequest) Reset() {
	*x = GetUserByCompanyIdRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByCompanyIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByCompanyIdRequest) ProtoMessage() {}

func (x *GetUserByCompanyIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByCompanyIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByCompanyIdRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserByCompanyIdRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetUserByCompanyIdRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type GetUserByCompanyIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByCompanyIdResponse) Reset() {
	*x = GetUserByCompanyIdResponse{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByCompanyIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByCompanyIdResponse) ProtoMessage() {}

func (x *GetUserByCompanyIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByCompanyIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserByCompanyIdResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserByCompanyIdResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateUserPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPasswordRequest) Reset() {
	*x = UpdateUserPasswordRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPasswordRequest) ProtoMessage() {}

func (x *UpdateUserPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserPasswordRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserPasswordRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type GetAllStuffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stuff         []*GetUserByIdResponse `protobuf:"bytes,1,rep,name=stuff,proto3" json:"stuff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllStuffResponse) Reset() {
	*x = GetAllStuffResponse{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllStuffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllStuffResponse) ProtoMessage() {}

func (x *GetAllStuffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllStuffResponse.ProtoReflect.Descriptor instead.
func (*GetAllStuffResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllStuffResponse) GetStuff() []*GetUserByIdResponse {
	if x != nil {
		return x.Stuff
	}
	return nil
}

type GetHistoryByUserIdResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Histories     []*AbsGetHistoryByUserIdResponse `protobuf:"bytes,1,rep,name=histories,proto3" json:"histories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryByUserIdResponse) Reset() {
	*x = GetHistoryByUserIdResponse{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryByUserIdResponse) ProtoMessage() {}

func (x *GetHistoryByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryByUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetHistoryByUserIdResponse) GetHistories() []*AbsGetHistoryByUserIdResponse {
	if x != nil {
		return x.Histories
	}
	return nil
}

type AbsGetHistoryByUserIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedField  string                 `protobuf:"bytes,1,opt,name=updatedField,proto3" json:"updatedField,omitempty"`
	OldValue      string                 `protobuf:"bytes,2,opt,name=oldValue,proto3" json:"oldValue,omitempty"`
	CurrentValue  string                 `protobuf:"bytes,3,opt,name=currentValue,proto3" json:"currentValue,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbsGetHistoryByUserIdResponse) Reset() {
	*x = AbsGetHistoryByUserIdResponse{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsGetHistoryByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsGetHistoryByUserIdResponse) ProtoMessage() {}

func (x *AbsGetHistoryByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsGetHistoryByUserIdResponse.ProtoReflect.Descriptor instead.
func (*AbsGetHistoryByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *AbsGetHistoryByUserIdResponse) GetUpdatedField() string {
	if x != nil {
		return x.UpdatedField
	}
	return ""
}

func (x *AbsGetHistoryByUserIdResponse) GetOldValue() string {
	if x != nil {
		return x.OldValue
	}
	return ""
}

func (x *AbsGetHistoryByUserIdResponse) GetCurrentValue() string {
	if x != nil {
		return x.CurrentValue
	}
	return ""
}

func (x *AbsGetHistoryByUserIdResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	BirthDate     string                 `protobuf:"bytes,4,opt,name=birthDate,proto3" json:"birthDate,omitempty"`
	Gender        bool                   `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Password      string                 `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UpdateUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UpdateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserRequest) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *UpdateUserRequest) GetGender() bool {
	if x != nil {
		return x.Gender
	}
	return false
}

func (x *UpdateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GetAllEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsArchived    bool                   `protobuf:"varint,1,opt,name=isArchived,proto3" json:"isArchived,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllEmployeeRequest) Reset() {
	*x = GetAllEmployeeRequest{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllEmployeeRequest) ProtoMessage() {}

func (x *GetAllEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllEmployeeRequest.ProtoReflect.Descriptor instead.
func (*GetAllEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllEmployeeRequest) GetIsArchived() bool {
	if x != nil {
		return x.IsArchived
	}
	return false
}

type GetAllEmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employees     []*GetUserByIdResponse `protobuf:"bytes,1,rep,name=employees,proto3" json:"employees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllEmployeeResponse) Reset() {
	*x = GetAllEmployeeResponse{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllEmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllEmployeeResponse) ProtoMessage() {}

func (x *GetAllEmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllEmployeeResponse.ProtoReflect.Descriptor instead.
func (*GetAllEmployeeResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllEmployeeResponse) GetEmployees() []*GetUserByIdResponse {
	if x != nil {
		return x.Employees
	}
	return nil
}

type UserAbsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAbsRequest) Reset() {
	*x = UserAbsRequest{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAbsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAbsRequest) ProtoMessage() {}

func (x *UserAbsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAbsRequest.ProtoReflect.Descriptor instead.
func (*UserAbsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *UserAbsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserByIdResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PhoneNumber      string                 `protobuf:"bytes,2,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Role             string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Name             string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	BirthDate        string                 `protobuf:"bytes,5,opt,name=birthDate,proto3" json:"birthDate,omitempty"`
	Gender           bool                   `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	IsDeleted        bool                   `protobuf:"varint,7,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	CompanyId        int32                  `protobuf:"varint,9,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	HasAccessFinance bool                   `protobuf:"varint,10,opt,name=has_access_finance,json=hasAccessFinance,proto3" json:"has_access_finance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetUserByIdResponse) Reset() {
	*x = GetUserByIdResponse{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdResponse) ProtoMessage() {}

func (x *GetUserByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIdResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserByIdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserByIdResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *GetUserByIdResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetUserByIdResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserByIdResponse) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *GetUserByIdResponse) GetGender() bool {
	if x != nil {
		return x.Gender
	}
	return false
}

func (x *GetUserByIdResponse) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *GetUserByIdResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetUserByIdResponse) GetCompanyId() int32 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *GetUserByIdResponse) GetHasAccessFinance() bool {
	if x != nil {
		return x.HasAccessFinance
	}
	return false
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=fullName,proto3" json:"fullName,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	BirthDate     string                 `protobuf:"bytes,5,opt,name=birthDate,proto3" json:"birthDate,omitempty"`
	Gender        bool                   `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *CreateUserRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateUserRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateUserRequest) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *CreateUserRequest) GetGender() bool {
	if x != nil {
		return x.Gender
	}
	return false
}

type GetTeachersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDeleted     bool                   `protobuf:"varint,1,opt,name=isDeleted,proto3" json:"isDeleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeachersRequest) Reset() {
	*x = GetTeachersRequest{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeachersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeachersRequest) ProtoMessage() {}

func (x *GetTeachersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeachersRequest.ProtoReflect.Descriptor instead.
func (*GetTeachersRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetTeachersRequest) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type GetTeachersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teachers      []*AbsTeacher          `protobuf:"bytes,1,rep,name=teachers,proto3" json:"teachers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeachersResponse) Reset() {
	*x = GetTeachersResponse{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeachersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeachersResponse) ProtoMessage() {}

func (x *GetTeachersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeachersResponse.ProtoReflect.Descriptor instead.
func (*GetTeachersResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetTeachersResponse) GetTeachers() []*AbsTeacher {
	if x != nil {
		return x.Teachers
	}
	return nil
}

type AbsTeacher struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,1,opt,name=fullName,proto3" json:"fullName,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	ActiveGroups  string                 `protobuf:"bytes,3,opt,name=activeGroups,proto3" json:"activeGroups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbsTeacher) Reset() {
	*x = AbsTeacher{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsTeacher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsTeacher) ProtoMessage() {}

func (x *AbsTeacher) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsTeacher.ProtoReflect.Descriptor instead.
func (*AbsTeacher) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *AbsTeacher) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AbsTeacher) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *AbsTeacher) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *AbsTeacher) GetActiveGroups() string {
	if x != nil {
		return x.ActiveGroups
	}
	return ""
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RequiredRoles []string               `protobuf:"bytes,2,rep,name=requiredRoles,proto3" json:"requiredRoles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ValidateTokenRequest) GetRequiredRoles() []string {
	if x != nil {
		return x.RequiredRoles
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	CompanyId     string                 `protobuf:"bytes,3,opt,name=companyId,proto3" json:"companyId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *LoginRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *GetUserByIdResponse   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	IsOk          bool                   `protobuf:"varint,3,opt,name=isOk,proto3" json:"isOk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *LoginResponse) GetUser() *GetUserByIdResponse {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\x1a\fcommon.proto\"M\n" +
	"\x19GetUserByCompanyIdRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x1c\n" +
	"\tcompanyId\x18\x02 \x01(\tR\tcompanyId\"4\n" +
	"\x1aGetUserByCompanyIdResponse\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"U\n" +
	"\x19UpdateUserPasswordRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\vnewPassword\x18\x02 \x01(\tR\vnewPassword\"F\n" +
	"\x13GetAllStuffResponse\x12/\n" +
	"\x05stuff\x18\x01 \x03(\v2\x19.user.GetUserByIdResponseR\x05stuff\"_\n" +
	"\x1aGetHistoryByUserIdResponse\x12A\n" +
	"\thistories\x18\x01 \x03(\v2#.user.AbsGetHistoryByUserIdResponseR\thistories\"\xa1\x01\n" +
	"\x1dAbsGetHistoryByUserIdResponse\x12\"\n" +
	"\fupdatedField\x18\x01 \x01(\tR\fupdatedField\x12\x1a\n" +
	"\boldValue\x18\x02 \x01(\tR\boldValue\x12\"\n" +
	"\fcurrentValue\x18\x03 \x01(\tR\fcurrentValue\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\tR\tcreatedAt\"\xbf\x01\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\x12 \n" +
	"\vphoneNumber\x18\x01 \x01(\tR\vphoneNumber\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tbirthDate\x18\x04 \x01(\tR\tbirthDate\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\bR\x06gender\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\"7\n" +
	"\x15GetAllEmployeeRequest\x12\x1e\n" +
	"\n" +
	"isArchived\x18\x01 \x01(\bR\n" +
	"isArchived\"Q\n" +
	"\x16GetAllEmployeeResponse\x127\n" +
	"\temployees\x18\x01 \x03(\v2\x19.user.GetUserByIdResponseR\temployees\"(\n" +
	"\x0eUserAbsRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"\xaf\x02\n" +
	"\x13GetUserByIdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vphoneNumber\x18\x02 \x01(\tR\vphoneNumber\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1c\n" +
	"\tbirthDate\x18\x05 \x01(\tR\tbirthDate\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\bR\x06gender\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\a \x01(\bR\tisDeleted\x12\x1c\n" +
	"\tcreatedAt\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"company_id\x18\t \x01(\x05R\tcompanyId\x12,\n" +
	"\x12has_access_finance\x18\n" +
	" \x01(\bR\x10hasAccessFinance\"\xb7\x01\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\bfullName\x18\x01 \x01(\tR\bfullName\x12 \n" +
	"\vphoneNumber\x18\x02 \x01(\tR\vphoneNumber\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1c\n" +
	"\tbirthDate\x18\x05 \x01(\tR\tbirthDate\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\bR\x06gender\"2\n" +
	"\x12GetTeachersRequest\x12\x1c\n" +
	"\tisDeleted\x18\x01 \x01(\bR\tisDeleted\"C\n" +
	"\x13GetTeachersResponse\x12,\n" +
	"\bteachers\x18\x01 \x03(\v2\x10.user.AbsTeacherR\bteachers\"~\n" +
	"\n" +
	"AbsTeacher\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x1a\n" +
	"\bfullName\x18\x01 \x01(\tR\bfullName\x12 \n" +
	"\vphoneNumber\x18\x02 \x01(\tR\vphoneNumber\x12\"\n" +
	"\factiveGroups\x18\x03 \x01(\tR\factiveGroups\"R\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12$\n" +
	"\rrequiredRoles\x18\x02 \x03(\tR\rrequiredRoles\"j\n" +
	"\fLoginRequest\x12 \n" +
	"\vphoneNumber\x18\x01 \x01(\tR\vphoneNumber\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1c\n" +
	"\tcompanyId\x18\x03 \x01(\tR\tcompanyId\"h\n" +
	"\rLoginResponse\x12-\n" +
	"\x04user\x18\x01 \x01(\v2\x19.user.GetUserByIdResponseR\x04user\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x12\n" +
	"\x04isOk\x18\x03 \x01(\bR\x04isOk2\xd1\x05\n" +
	"\vUserService\x12:\n" +
	"\n" +
	"CreateUser\x12\x17.user.CreateUserRequest\x1a\x13.common.AbsResponse\x12B\n" +
	"\vGetTeachers\x12\x18.user.GetTeachersRequest\x1a\x19.user.GetTeachersResponse\x12>\n" +
	"\vGetUserById\x12\x14.user.UserAbsRequest\x1a\x19.user.GetUserByIdResponse\x12>\n" +
	"\x0eUpdateUserById\x12\x17.user.UpdateUserRequest\x1a\x13.common.AbsResponse\x12;\n" +
	"\x0eDeleteUserById\x12\x14.user.UserAbsRequest\x1a\x13.common.AbsResponse\x12K\n" +
	"\x0eGetAllEmployee\x12\x1b.user.GetAllEmployeeRequest\x1a\x1c.user.GetAllEmployeeResponse\x12E\n" +
	"\vGetAllStuff\x12\x1b.user.GetAllEmployeeRequest\x1a\x19.user.GetAllStuffResponse\x12L\n" +
	"\x12GetHistoryByUserId\x12\x14.user.UserAbsRequest\x1a .user.GetHistoryByUserIdResponse\x12J\n" +
	"\x12UpdateUserPassword\x12\x1f.user.UpdateUserPasswordRequest\x1a\x13.common.AbsResponse\x12W\n" +
	"\x12GetUserByCompanyId\x12\x1f.user.GetUserByCompanyIdRequest\x1a .user.GetUserByCompanyIdResponse2\x87\x01\n" +
	"\vAuthService\x120\n" +
	"\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\x12F\n" +
	"\rValidateToken\x12\x1a.user.ValidateTokenRequest\x1a\x19.user.GetUserByIdResponseB\n" +
	"Z\bproto/pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_user_proto_goTypes = []any{
	(*GetUserByCompanyIdRequest)(nil),     // 0: user.GetUserByCompanyIdRequest
	(*GetUserByCompanyIdResponse)(nil),    // 1: user.GetUserByCompanyIdResponse
	(*UpdateUserPasswordRequest)(nil),     // 2: user.UpdateUserPasswordRequest
	(*GetAllStuffResponse)(nil),           // 3: user.GetAllStuffResponse
	(*GetHistoryByUserIdResponse)(nil),    // 4: user.GetHistoryByUserIdResponse
	(*AbsGetHistoryByUserIdResponse)(nil), // 5: user.AbsGetHistoryByUserIdResponse
	(*UpdateUserRequest)(nil),             // 6: user.UpdateUserRequest
	(*GetAllEmployeeRequest)(nil),         // 7: user.GetAllEmployeeRequest
	(*GetAllEmployeeResponse)(nil),        // 8: user.GetAllEmployeeResponse
	(*UserAbsRequest)(nil),                // 9: user.UserAbsRequest
	(*GetUserByIdResponse)(nil),           // 10: user.GetUserByIdResponse
	(*CreateUserRequest)(nil),             // 11: user.CreateUserRequest
	(*GetTeachersRequest)(nil),            // 12: user.GetTeachersRequest
	(*GetTeachersResponse)(nil),           // 13: user.GetTeachersResponse
	(*AbsTeacher)(nil),                    // 14: user.AbsTeacher
	(*ValidateTokenRequest)(nil),          // 15: user.ValidateTokenRequest
	(*LoginRequest)(nil),                  // 16: user.LoginRequest
	(*LoginResponse)(nil),                 // 17: user.LoginResponse
	(*AbsResponse)(nil),                   // 18: common.AbsResponse
}
var file_user_proto_depIdxs = []int32{
	10, // 0: user.GetAllStuffResponse.stuff:type_name -> user.GetUserByIdResponse
	5,  // 1: user.GetHistoryByUserIdResponse.histories:type_name -> user.AbsGetHistoryByUserIdResponse
	10, // 2: user.GetAllEmployeeResponse.employees:type_name -> user.GetUserByIdResponse
	14, // 3: user.GetTeachersResponse.teachers:type_name -> user.AbsTeacher
	10, // 4: user.LoginResponse.user:type_name -> user.GetUserByIdResponse
	11, // 5: user.UserService.CreateUser:input_type -> user.CreateUserRequest
	12, // 6: user.UserService.GetTeachers:input_type -> user.GetTeachersRequest
	9,  // 7: user.UserService.GetUserById:input_type -> user.UserAbsRequest
	6,  // 8: user.UserService.UpdateUserById:input_type -> user.UpdateUserRequest
	9,  // 9: user.UserService.DeleteUserById:input_type -> user.UserAbsRequest
	7,  // 10: user.UserService.GetAllEmployee:input_type -> user.GetAllEmployeeRequest
	7,  // 11: user.UserService.GetAllStuff:input_type -> user.GetAllEmployeeRequest
	9,  // 12: user.UserService.GetHistoryByUserId:input_type -> user.UserAbsRequest
	2,  // 13: user.UserService.UpdateUserPassword:input_type -> user.UpdateUserPasswordRequest
	0,  // 14: user.UserService.GetUserByCompanyId:input_type -> user.GetUserByCompanyIdRequest
	16, // 15: user.AuthService.Login:input_type -> user.LoginRequest
	15, // 16: user.AuthService.ValidateToken:input_type -> user.ValidateTokenRequest
	18, // 17: user.UserService.CreateUser:output_type -> common.AbsResponse
	13, // 18: user.UserService.GetTeachers:output_type -> user.GetTeachersResponse
	10, // 19: user.UserService.GetUserById:output_type -> user.GetUserByIdResponse
	18, // 20: user.UserService.UpdateUserById:output_type -> common.AbsResponse
	18, // 21: user.UserService.DeleteUserById:output_type -> common.AbsResponse
	8,  // 22: user.UserService.GetAllEmployee:output_type -> user.GetAllEmployeeResponse
	3,  // 23: user.UserService.GetAllStuff:output_type -> user.GetAllStuffResponse
	4,  // 24: user.UserService.GetHistoryByUserId:output_type -> user.GetHistoryByUserIdResponse
	18, // 25: user.UserService.UpdateUserPassword:output_type -> common.AbsResponse
	1,  // 26: user.UserService.GetUserByCompanyId:output_type -> user.GetUserByCompanyIdResponse
	17, // 27: user.AuthService.Login:output_type -> user.LoginResponse
	10, // 28: user.AuthService.ValidateToken:output_type -> user.GetUserByIdResponse
	17, // [17:29] is the sub-list for method output_type
	5,  // [5:17] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
