// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: finance.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDiscountByStudentIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        string                 `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	IsHave        bool                   `protobuf:"varint,2,opt,name=isHave,proto3" json:"isHave,omitempty"`
	DiscountOwner string                 `protobuf:"bytes,3,opt,name=discountOwner,proto3" json:"discountOwner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiscountByStudentIdResponse) Reset() {
	*x = GetDiscountByStudentIdResponse{}
	mi := &file_finance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiscountByStudentIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiscountByStudentIdResponse) ProtoMessage() {}

func (x *GetDiscountByStudentIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiscountByStudentIdResponse.ProtoReflect.Descriptor instead.
func (*GetDiscountByStudentIdResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{0}
}

func (x *GetDiscountByStudentIdResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *GetDiscountByStudentIdResponse) GetIsHave() bool {
	if x != nil {
		return x.IsHave
	}
	return false
}

func (x *GetDiscountByStudentIdResponse) GetDiscountOwner() string {
	if x != nil {
		return x.DiscountOwner
	}
	return ""
}

type GetDiscountByStudentIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiscountByStudentIdRequest) Reset() {
	*x = GetDiscountByStudentIdRequest{}
	mi := &file_finance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiscountByStudentIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiscountByStudentIdRequest) ProtoMessage() {}

func (x *GetDiscountByStudentIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiscountByStudentIdRequest.ProtoReflect.Descriptor instead.
func (*GetDiscountByStudentIdRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{1}
}

func (x *GetDiscountByStudentIdRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *GetDiscountByStudentIdRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type PaymentAddRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Comment              string                 `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	Date                 string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Method               string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Sum                  string                 `protobuf:"bytes,4,opt,name=sum,proto3" json:"sum,omitempty"`
	UserId               string                 `protobuf:"bytes,5,opt,name=userId,proto3" json:"userId,omitempty"`
	Type                 string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	ActionById           string                 `protobuf:"bytes,7,opt,name=actionById,proto3" json:"actionById,omitempty"`
	ActionByName         string                 `protobuf:"bytes,8,opt,name=actionByName,proto3" json:"actionByName,omitempty"`
	GroupId              string                 `protobuf:"bytes,9,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Studentconditiondate string                 `protobuf:"bytes,10,opt,name=studentconditiondate,proto3" json:"studentconditiondate,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PaymentAddRequest) Reset() {
	*x = PaymentAddRequest{}
	mi := &file_finance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentAddRequest) ProtoMessage() {}

func (x *PaymentAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentAddRequest.ProtoReflect.Descriptor instead.
func (*PaymentAddRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentAddRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *PaymentAddRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *PaymentAddRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PaymentAddRequest) GetSum() string {
	if x != nil {
		return x.Sum
	}
	return ""
}

func (x *PaymentAddRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PaymentAddRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PaymentAddRequest) GetActionById() string {
	if x != nil {
		return x.ActionById
	}
	return ""
}

func (x *PaymentAddRequest) GetActionByName() string {
	if x != nil {
		return x.ActionByName
	}
	return ""
}

func (x *PaymentAddRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *PaymentAddRequest) GetStudentconditiondate() string {
	if x != nil {
		return x.Studentconditiondate
	}
	return ""
}

type DeleteTeacherSalaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeacherId     string                 `protobuf:"bytes,1,opt,name=teacherId,proto3" json:"teacherId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeacherSalaryRequest) Reset() {
	*x = DeleteTeacherSalaryRequest{}
	mi := &file_finance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeacherSalaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeacherSalaryRequest) ProtoMessage() {}

func (x *DeleteTeacherSalaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeacherSalaryRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeacherSalaryRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteTeacherSalaryRequest) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

type AbsGetTeachersSalary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeacherId     string                 `protobuf:"bytes,1,opt,name=teacherId,proto3" json:"teacherId,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	TeacherName   string                 `protobuf:"bytes,4,opt,name=teacherName,proto3" json:"teacherName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbsGetTeachersSalary) Reset() {
	*x = AbsGetTeachersSalary{}
	mi := &file_finance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsGetTeachersSalary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsGetTeachersSalary) ProtoMessage() {}

func (x *AbsGetTeachersSalary) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsGetTeachersSalary.ProtoReflect.Descriptor instead.
func (*AbsGetTeachersSalary) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{4}
}

func (x *AbsGetTeachersSalary) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *AbsGetTeachersSalary) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AbsGetTeachersSalary) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AbsGetTeachersSalary) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

var File_finance_proto protoreflect.FileDescriptor

const file_finance_proto_rawDesc = "" +
	"\n" +
	"\rfinance.proto\x12\afinance\x1a\fcommon.proto\"v\n" +
	"\x1eGetDiscountByStudentIdResponse\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\x12\x16\n" +
	"\x06isHave\x18\x02 \x01(\bR\x06isHave\x12$\n" +
	"\rdiscountOwner\x18\x03 \x01(\tR\rdiscountOwner\"W\n" +
	"\x1dGetDiscountByStudentIdRequest\x12\x1c\n" +
	"\tstudentId\x18\x01 \x01(\tR\tstudentId\x12\x18\n" +
	"\agroupId\x18\x02 \x01(\tR\agroupId\"\xa9\x02\n" +
	"\x11PaymentAddRequest\x12\x18\n" +
	"\acomment\x18\x01 \x01(\tR\acomment\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x10\n" +
	"\x03sum\x18\x04 \x01(\tR\x03sum\x12\x16\n" +
	"\x06userId\x18\x05 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"actionById\x18\a \x01(\tR\n" +
	"actionById\x12\"\n" +
	"\factionByName\x18\b \x01(\tR\factionByName\x12\x18\n" +
	"\agroupId\x18\t \x01(\tR\agroupId\x122\n" +
	"\x14studentconditiondate\x18\n" +
	" \x01(\tR\x14studentconditiondate\":\n" +
	"\x1aDeleteTeacherSalaryRequest\x12\x1c\n" +
	"\tteacherId\x18\x01 \x01(\tR\tteacherId\"\x82\x01\n" +
	"\x14AbsGetTeachersSalary\x12\x1c\n" +
	"\tteacherId\x18\x01 \x01(\tR\tteacherId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\x12 \n" +
	"\vteacherName\x18\x04 \x01(\tR\vteacherName2|\n" +
	"\x0fDiscountService\x12i\n" +
	"\x16GetDiscountByStudentId\x12&.finance.GetDiscountByStudentIdRequest\x1a'.finance.GetDiscountByStudentIdResponse2O\n" +
	"\x0ePaymentService\x12=\n" +
	"\n" +
	"PaymentAdd\x12\x1a.finance.PaymentAddRequest\x1a\x13.common.AbsResponse2y\n" +
	"\x14TeacherSalaryService\x12a\n" +
	"\x1bGetTeacherSalaryByTeacherID\x12#.finance.DeleteTeacherSalaryRequest\x1a\x1d.finance.AbsGetTeachersSalaryB\n" +
	"Z\bproto/pbb\x06proto3"

var (
	file_finance_proto_rawDescOnce sync.Once
	file_finance_proto_rawDescData []byte
)

func file_finance_proto_rawDescGZIP() []byte {
	file_finance_proto_rawDescOnce.Do(func() {
		file_finance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_finance_proto_rawDesc), len(file_finance_proto_rawDesc)))
	})
	return file_finance_proto_rawDescData
}

var file_finance_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_finance_proto_goTypes = []any{
	(*GetDiscountByStudentIdResponse)(nil), // 0: finance.GetDiscountByStudentIdResponse
	(*GetDiscountByStudentIdRequest)(nil),  // 1: finance.GetDiscountByStudentIdRequest
	(*PaymentAddRequest)(nil),              // 2: finance.PaymentAddRequest
	(*DeleteTeacherSalaryRequest)(nil),     // 3: finance.DeleteTeacherSalaryRequest
	(*AbsGetTeachersSalary)(nil),           // 4: finance.AbsGetTeachersSalary
	(*AbsResponse)(nil),                    // 5: common.AbsResponse
}
var file_finance_proto_depIdxs = []int32{
	1, // 0: finance.DiscountService.GetDiscountByStudentId:input_type -> finance.GetDiscountByStudentIdRequest
	2, // 1: finance.PaymentService.PaymentAdd:input_type -> finance.PaymentAddRequest
	3, // 2: finance.TeacherSalaryService.GetTeacherSalaryByTeacherID:input_type -> finance.DeleteTeacherSalaryRequest
	0, // 3: finance.DiscountService.GetDiscountByStudentId:output_type -> finance.GetDiscountByStudentIdResponse
	5, // 4: finance.PaymentService.PaymentAdd:output_type -> common.AbsResponse
	4, // 5: finance.TeacherSalaryService.GetTeacherSalaryByTeacherID:output_type -> finance.AbsGetTeachersSalary
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_finance_proto_init() }
func file_finance_proto_init() {
	if File_finance_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_finance_proto_rawDesc), len(file_finance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_finance_proto_goTypes,
		DependencyIndexes: file_finance_proto_depIdxs,
		MessageInfos:      file_finance_proto_msgTypes,
	}.Build()
	File_finance_proto = out.File
	file_finance_proto_goTypes = nil
	file_finance_proto_depIdxs = nil
}
