// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: education.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AbsRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Capacity      int32                  `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbsRoom) Reset() {
	*x = AbsRoom{}
	mi := &file_education_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsRoom) ProtoMessage() {}

func (x *AbsRoom) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsRoom.ProtoReflect.Descriptor instead.
func (*AbsRoom) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{0}
}

func (x *AbsRoom) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AbsRoom) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *AbsRoom) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AbsCourse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LessonDuration int32                  `protobuf:"varint,2,opt,name=lessonDuration,proto3" json:"lessonDuration,omitempty"`
	CourseDuration int32                  `protobuf:"varint,3,opt,name=courseDuration,proto3" json:"courseDuration,omitempty"`
	Price          float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AbsCourse) Reset() {
	*x = AbsCourse{}
	mi := &file_education_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsCourse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsCourse) ProtoMessage() {}

func (x *AbsCourse) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsCourse.ProtoReflect.Descriptor instead.
func (*AbsCourse) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{1}
}

func (x *AbsCourse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AbsCourse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AbsCourse) GetLessonDuration() int32 {
	if x != nil {
		return x.LessonDuration
	}
	return 0
}

func (x *AbsCourse) GetCourseDuration() int32 {
	if x != nil {
		return x.CourseDuration
	}
	return 0
}

func (x *AbsCourse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AbsCourse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CalculateDiscountSummaRequest struct {
	state                                        protoimpl.MessageState `protogen:"open.v1"`
	GroupId                                      string                 `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	StudentId                                    string                 `protobuf:"bytes,2,opt,name=studentId,proto3" json:"studentId,omitempty"`
	DiscountPrice                                string                 `protobuf:"bytes,3,opt,name=discountPrice,proto3" json:"discountPrice,omitempty"`
	StartDate                                    string                 `protobuf:"bytes,4,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate                                      string                 `protobuf:"bytes,5,opt,name=endDate,proto3" json:"endDate,omitempty"`
	PaymentDate                                  string                 `protobuf:"bytes,6,opt,name=paymentDate,proto3" json:"paymentDate,omitempty"`
	StudentActivationDateInThisGroupWhilePayment string                 `protobuf:"bytes,7,opt,name=studentActivationDateInThisGroupWhilePayment,proto3" json:"studentActivationDateInThisGroupWhilePayment,omitempty"`
	unknownFields                                protoimpl.UnknownFields
	sizeCache                                    protoimpl.SizeCache
}

func (x *CalculateDiscountSummaRequest) Reset() {
	*x = CalculateDiscountSummaRequest{}
	mi := &file_education_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateDiscountSummaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateDiscountSummaRequest) ProtoMessage() {}

func (x *CalculateDiscountSummaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateDiscountSummaRequest.ProtoReflect.Descriptor instead.
func (*CalculateDiscountSummaRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{2}
}

func (x *CalculateDiscountSummaRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CalculateDiscountSummaRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *CalculateDiscountSummaRequest) GetDiscountPrice() string {
	if x != nil {
		return x.DiscountPrice
	}
	return ""
}

func (x *CalculateDiscountSummaRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CalculateDiscountSummaRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *CalculateDiscountSummaRequest) GetPaymentDate() string {
	if x != nil {
		return x.PaymentDate
	}
	return ""
}

func (x *CalculateDiscountSummaRequest) GetStudentActivationDateInThisGroupWhilePayment() string {
	if x != nil {
		return x.StudentActivationDateInThisGroupWhilePayment
	}
	return ""
}

type CalculateDiscountResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CalculatedPrice string                 `protobuf:"bytes,1,opt,name=calculatedPrice,proto3" json:"calculatedPrice,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CalculateDiscountResponse) Reset() {
	*x = CalculateDiscountResponse{}
	mi := &file_education_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateDiscountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateDiscountResponse) ProtoMessage() {}

func (x *CalculateDiscountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateDiscountResponse.ProtoReflect.Descriptor instead.
func (*CalculateDiscountResponse) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{3}
}

func (x *CalculateDiscountResponse) GetCalculatedPrice() string {
	if x != nil {
		return x.CalculatedPrice
	}
	return ""
}

type ChangeUserBalanceHistoryByDebitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
	OldDebit      string                 `protobuf:"bytes,2,opt,name=oldDebit,proto3" json:"oldDebit,omitempty"`
	GivenDate     string                 `protobuf:"bytes,3,opt,name=givenDate,proto3" json:"givenDate,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	PaymentType   string                 `protobuf:"bytes,5,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,6,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	CreatedByName string                 `protobuf:"bytes,7,opt,name=createdByName,proto3" json:"createdByName,omitempty"`
	GroupId       string                 `protobuf:"bytes,8,opt,name=groupId,proto3" json:"groupId,omitempty"`
	CurrentDebit  string                 `protobuf:"bytes,9,opt,name=currentDebit,proto3" json:"currentDebit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserBalanceHistoryByDebitRequest) Reset() {
	*x = ChangeUserBalanceHistoryByDebitRequest{}
	mi := &file_education_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserBalanceHistoryByDebitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserBalanceHistoryByDebitRequest) ProtoMessage() {}

func (x *ChangeUserBalanceHistoryByDebitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserBalanceHistoryByDebitRequest.ProtoReflect.Descriptor instead.
func (*ChangeUserBalanceHistoryByDebitRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{4}
}

func (x *ChangeUserBalanceHistoryByDebitRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *ChangeUserBalanceHistoryByDebitRequest) GetOldDebit() string {
	if x != nil {
		return x.OldDebit
	}
	return ""
}

func (x *ChangeUserBalanceHistoryByDebitRequest) GetGivenDate() string {
	if x != nil {
		return x.GivenDate
	}
	return ""
}

func (x *ChangeUserBalanceHistoryByDebitRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ChangeUserBalanceHistoryByDebitRequest) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *ChangeUserBalanceHistoryByDebitRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ChangeUserBalanceHistoryByDebitRequest) GetCreatedByName() string {
	if x != nil {
		return x.CreatedByName
	}
	return ""
}

func (x *ChangeUserBalanceHistoryByDebitRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ChangeUserBalanceHistoryByDebitRequest) GetCurrentDebit() string {
	if x != nil {
		return x.CurrentDebit
	}
	return ""
}

type ChangeUserBalanceHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	GivenDate     string                 `protobuf:"bytes,3,opt,name=givenDate,proto3" json:"givenDate,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	PaymentType   string                 `protobuf:"bytes,5,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,6,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	CreatedByName string                 `protobuf:"bytes,7,opt,name=createdByName,proto3" json:"createdByName,omitempty"`
	GroupId       string                 `protobuf:"bytes,8,opt,name=groupId,proto3" json:"groupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserBalanceHistoryRequest) Reset() {
	*x = ChangeUserBalanceHistoryRequest{}
	mi := &file_education_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserBalanceHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserBalanceHistoryRequest) ProtoMessage() {}

func (x *ChangeUserBalanceHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserBalanceHistoryRequest.ProtoReflect.Descriptor instead.
func (*ChangeUserBalanceHistoryRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{5}
}

func (x *ChangeUserBalanceHistoryRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *ChangeUserBalanceHistoryRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *ChangeUserBalanceHistoryRequest) GetGivenDate() string {
	if x != nil {
		return x.GivenDate
	}
	return ""
}

func (x *ChangeUserBalanceHistoryRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ChangeUserBalanceHistoryRequest) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *ChangeUserBalanceHistoryRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ChangeUserBalanceHistoryRequest) GetCreatedByName() string {
	if x != nil {
		return x.CreatedByName
	}
	return ""
}

func (x *ChangeUserBalanceHistoryRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GetStudentsByGroupIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Students      []*AbsStudent          `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentsByGroupIdResponse) Reset() {
	*x = GetStudentsByGroupIdResponse{}
	mi := &file_education_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentsByGroupIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentsByGroupIdResponse) ProtoMessage() {}

func (x *GetStudentsByGroupIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentsByGroupIdResponse.ProtoReflect.Descriptor instead.
func (*GetStudentsByGroupIdResponse) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{6}
}

func (x *GetStudentsByGroupIdResponse) GetStudents() []*AbsStudent {
	if x != nil {
		return x.Students
	}
	return nil
}

type GetStudentsByGroupIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	WithOutdated  bool                   `protobuf:"varint,2,opt,name=withOutdated,proto3" json:"withOutdated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentsByGroupIdRequest) Reset() {
	*x = GetStudentsByGroupIdRequest{}
	mi := &file_education_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentsByGroupIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentsByGroupIdRequest) ProtoMessage() {}

func (x *GetStudentsByGroupIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentsByGroupIdRequest.ProtoReflect.Descriptor instead.
func (*GetStudentsByGroupIdRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{7}
}

func (x *GetStudentsByGroupIdRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GetStudentsByGroupIdRequest) GetWithOutdated() bool {
	if x != nil {
		return x.WithOutdated
	}
	return false
}

type AbsStudent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbsStudent) Reset() {
	*x = AbsStudent{}
	mi := &file_education_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsStudent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsStudent) ProtoMessage() {}

func (x *AbsStudent) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsStudent.ProtoReflect.Descriptor instead.
func (*AbsStudent) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{8}
}

func (x *AbsStudent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AbsStudent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AbsStudent) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type GetStudentByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gender        bool                   `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,4,opt,name=dateOfBirth,proto3" json:"dateOfBirth,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Balance       float64                `protobuf:"fixed64,6,opt,name=balance,proto3" json:"balance,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Groups        []*GetGroupStudent     `protobuf:"bytes,8,rep,name=groups,proto3" json:"groups,omitempty"`
	Condition     string                 `protobuf:"bytes,9,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentByIdResponse) Reset() {
	*x = GetStudentByIdResponse{}
	mi := &file_education_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentByIdResponse) ProtoMessage() {}

func (x *GetStudentByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentByIdResponse.ProtoReflect.Descriptor instead.
func (*GetStudentByIdResponse) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{9}
}

func (x *GetStudentByIdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetStudentByIdResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetStudentByIdResponse) GetGender() bool {
	if x != nil {
		return x.Gender
	}
	return false
}

func (x *GetStudentByIdResponse) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *GetStudentByIdResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetStudentByIdResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetStudentByIdResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetStudentByIdResponse) GetGroups() []*GetGroupStudent {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *GetStudentByIdResponse) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

type NoteStudentByAbsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteStudentByAbsRequest) Reset() {
	*x = NoteStudentByAbsRequest{}
	mi := &file_education_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteStudentByAbsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteStudentByAbsRequest) ProtoMessage() {}

func (x *NoteStudentByAbsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteStudentByAbsRequest.ProtoReflect.Descriptor instead.
func (*NoteStudentByAbsRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{10}
}

func (x *NoteStudentByAbsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetGroupStudent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DateType           string                 `protobuf:"bytes,3,opt,name=dateType,proto3" json:"dateType,omitempty"`
	Days               []string               `protobuf:"bytes,4,rep,name=days,proto3" json:"days,omitempty"`
	Room               *AbsRoom               `protobuf:"bytes,5,opt,name=room,proto3" json:"room,omitempty"`
	Course             *AbsCourse             `protobuf:"bytes,6,opt,name=course,proto3" json:"course,omitempty"`
	LessonStartTime    string                 `protobuf:"bytes,7,opt,name=lessonStartTime,proto3" json:"lessonStartTime,omitempty"`
	GroupStartDate     string                 `protobuf:"bytes,8,opt,name=groupStartDate,proto3" json:"groupStartDate,omitempty"`
	GroupEndDate       string                 `protobuf:"bytes,9,opt,name=groupEndDate,proto3" json:"groupEndDate,omitempty"`
	StudentCondition   string                 `protobuf:"bytes,11,opt,name=studentCondition,proto3" json:"studentCondition,omitempty"`
	StudentActivatedAt string                 `protobuf:"bytes,12,opt,name=studentActivatedAt,proto3" json:"studentActivatedAt,omitempty"`
	StudentAddedAt     string                 `protobuf:"bytes,14,opt,name=studentAddedAt,proto3" json:"studentAddedAt,omitempty"`
	TeacherName        string                 `protobuf:"bytes,15,opt,name=teacherName,proto3" json:"teacherName,omitempty"`
	PriceForStudent    float64                `protobuf:"fixed64,13,opt,name=priceForStudent,proto3" json:"priceForStudent,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetGroupStudent) Reset() {
	*x = GetGroupStudent{}
	mi := &file_education_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupStudent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupStudent) ProtoMessage() {}

func (x *GetGroupStudent) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupStudent.ProtoReflect.Descriptor instead.
func (*GetGroupStudent) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{11}
}

func (x *GetGroupStudent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetGroupStudent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetGroupStudent) GetDateType() string {
	if x != nil {
		return x.DateType
	}
	return ""
}

func (x *GetGroupStudent) GetDays() []string {
	if x != nil {
		return x.Days
	}
	return nil
}

func (x *GetGroupStudent) GetRoom() *AbsRoom {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *GetGroupStudent) GetCourse() *AbsCourse {
	if x != nil {
		return x.Course
	}
	return nil
}

func (x *GetGroupStudent) GetLessonStartTime() string {
	if x != nil {
		return x.LessonStartTime
	}
	return ""
}

func (x *GetGroupStudent) GetGroupStartDate() string {
	if x != nil {
		return x.GroupStartDate
	}
	return ""
}

func (x *GetGroupStudent) GetGroupEndDate() string {
	if x != nil {
		return x.GroupEndDate
	}
	return ""
}

func (x *GetGroupStudent) GetStudentCondition() string {
	if x != nil {
		return x.StudentCondition
	}
	return ""
}

func (x *GetGroupStudent) GetStudentActivatedAt() string {
	if x != nil {
		return x.StudentActivatedAt
	}
	return ""
}

func (x *GetGroupStudent) GetStudentAddedAt() string {
	if x != nil {
		return x.StudentAddedAt
	}
	return ""
}

func (x *GetGroupStudent) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

func (x *GetGroupStudent) GetPriceForStudent() float64 {
	if x != nil {
		return x.PriceForStudent
	}
	return 0
}

type StudentIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentIdRequest) Reset() {
	*x = StudentIdRequest{}
	mi := &file_education_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentIdRequest) ProtoMessage() {}

func (x *StudentIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentIdRequest.ProtoReflect.Descriptor instead.
func (*StudentIdRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{12}
}

func (x *StudentIdRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type GetGroupsByStudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*DebtorComment       `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	Groups        []*DebtorGroup         `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsByStudentResponse) Reset() {
	*x = GetGroupsByStudentResponse{}
	mi := &file_education_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsByStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsByStudentResponse) ProtoMessage() {}

func (x *GetGroupsByStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsByStudentResponse.ProtoReflect.Descriptor instead.
func (*GetGroupsByStudentResponse) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{13}
}

func (x *GetGroupsByStudentResponse) GetComments() []*DebtorComment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *GetGroupsByStudentResponse) GetGroups() []*DebtorGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GetGroupByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupByIdRequest) Reset() {
	*x = GetGroupByIdRequest{}
	mi := &file_education_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupByIdRequest) ProtoMessage() {}

func (x *GetGroupByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupByIdRequest.ProtoReflect.Descriptor instead.
func (*GetGroupByIdRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{14}
}

func (x *GetGroupByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetGroupAbsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TeacherName     string                 `protobuf:"bytes,3,opt,name=teacherName,proto3" json:"teacherName,omitempty"`
	TeacherId       string                 `protobuf:"bytes,14,opt,name=teacherId,proto3" json:"teacherId,omitempty"`
	LessonStartTime string                 `protobuf:"bytes,4,opt,name=lessonStartTime,proto3" json:"lessonStartTime,omitempty"`
	StudentCount    int32                  `protobuf:"varint,6,opt,name=studentCount,proto3" json:"studentCount,omitempty"`
	Name            string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	IsArchived      bool                   `protobuf:"varint,8,opt,name=isArchived,proto3" json:"isArchived,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	StartDate       string                 `protobuf:"bytes,10,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate         string                 `protobuf:"bytes,11,opt,name=endDate,proto3" json:"endDate,omitempty"`
	Days            []string               `protobuf:"bytes,12,rep,name=days,proto3" json:"days,omitempty"`
	DateType        string                 `protobuf:"bytes,13,opt,name=dateType,proto3" json:"dateType,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetGroupAbsResponse) Reset() {
	*x = GetGroupAbsResponse{}
	mi := &file_education_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupAbsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupAbsResponse) ProtoMessage() {}

func (x *GetGroupAbsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupAbsResponse.ProtoReflect.Descriptor instead.
func (*GetGroupAbsResponse) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{15}
}

func (x *GetGroupAbsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetGroupAbsResponse) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

func (x *GetGroupAbsResponse) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *GetGroupAbsResponse) GetLessonStartTime() string {
	if x != nil {
		return x.LessonStartTime
	}
	return ""
}

func (x *GetGroupAbsResponse) GetStudentCount() int32 {
	if x != nil {
		return x.StudentCount
	}
	return 0
}

func (x *GetGroupAbsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetGroupAbsResponse) GetIsArchived() bool {
	if x != nil {
		return x.IsArchived
	}
	return false
}

func (x *GetGroupAbsResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetGroupAbsResponse) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetGroupAbsResponse) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GetGroupAbsResponse) GetDays() []string {
	if x != nil {
		return x.Days
	}
	return nil
}

func (x *GetGroupAbsResponse) GetDateType() string {
	if x != nil {
		return x.DateType
	}
	return ""
}

var File_education_proto protoreflect.FileDescriptor

const file_education_proto_rawDesc = "" +
	"\n" +
	"\x0feducation.proto\x12\teducation\x1a\fcommon.proto\"I\n" +
	"\aAbsRoom\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\x05R\bcapacity\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xb7\x01\n" +
	"\tAbsCourse\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x0elessonDuration\x18\x02 \x01(\x05R\x0elessonDuration\x12&\n" +
	"\x0ecourseDuration\x18\x03 \x01(\x05R\x0ecourseDuration\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\xbb\x02\n" +
	"\x1dCalculateDiscountSummaRequest\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId\x12\x1c\n" +
	"\tstudentId\x18\x02 \x01(\tR\tstudentId\x12$\n" +
	"\rdiscountPrice\x18\x03 \x01(\tR\rdiscountPrice\x12\x1c\n" +
	"\tstartDate\x18\x04 \x01(\tR\tstartDate\x12\x18\n" +
	"\aendDate\x18\x05 \x01(\tR\aendDate\x12 \n" +
	"\vpaymentDate\x18\x06 \x01(\tR\vpaymentDate\x12b\n" +
	",studentActivationDateInThisGroupWhilePayment\x18\a \x01(\tR,studentActivationDateInThisGroupWhilePayment\"E\n" +
	"\x19CalculateDiscountResponse\x12(\n" +
	"\x0fcalculatedPrice\x18\x01 \x01(\tR\x0fcalculatedPrice\"\xbf\x02\n" +
	"&ChangeUserBalanceHistoryByDebitRequest\x12\x1c\n" +
	"\tstudentId\x18\x01 \x01(\tR\tstudentId\x12\x1a\n" +
	"\boldDebit\x18\x02 \x01(\tR\boldDebit\x12\x1c\n" +
	"\tgivenDate\x18\x03 \x01(\tR\tgivenDate\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12!\n" +
	"\fpayment_type\x18\x05 \x01(\tR\vpaymentType\x12\x1c\n" +
	"\tcreatedBy\x18\x06 \x01(\tR\tcreatedBy\x12$\n" +
	"\rcreatedByName\x18\a \x01(\tR\rcreatedByName\x12\x18\n" +
	"\agroupId\x18\b \x01(\tR\agroupId\x12\"\n" +
	"\fcurrentDebit\x18\t \x01(\tR\fcurrentDebit\"\x90\x02\n" +
	"\x1fChangeUserBalanceHistoryRequest\x12\x1c\n" +
	"\tstudentId\x18\x01 \x01(\tR\tstudentId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x1c\n" +
	"\tgivenDate\x18\x03 \x01(\tR\tgivenDate\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12!\n" +
	"\fpayment_type\x18\x05 \x01(\tR\vpaymentType\x12\x1c\n" +
	"\tcreatedBy\x18\x06 \x01(\tR\tcreatedBy\x12$\n" +
	"\rcreatedByName\x18\a \x01(\tR\rcreatedByName\x12\x18\n" +
	"\agroupId\x18\b \x01(\tR\agroupId\"Q\n" +
	"\x1cGetStudentsByGroupIdResponse\x121\n" +
	"\bstudents\x18\x01 \x03(\v2\x15.education.AbsStudentR\bstudents\"[\n" +
	"\x1bGetStudentsByGroupIdRequest\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId\x12\"\n" +
	"\fwithOutdated\x18\x02 \x01(\bR\fwithOutdated\"R\n" +
	"\n" +
	"AbsStudent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vphoneNumber\x18\x03 \x01(\tR\vphoneNumber\"\x96\x02\n" +
	"\x16GetStudentByIdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\bR\x06gender\x12 \n" +
	"\vdateOfBirth\x18\x04 \x01(\tR\vdateOfBirth\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x18\n" +
	"\abalance\x18\x06 \x01(\x01R\abalance\x12\x1c\n" +
	"\tcreatedAt\x18\a \x01(\tR\tcreatedAt\x122\n" +
	"\x06groups\x18\b \x03(\v2\x1a.education.GetGroupStudentR\x06groups\x12\x1c\n" +
	"\tcondition\x18\t \x01(\tR\tcondition\")\n" +
	"\x17NoteStudentByAbsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x81\x04\n" +
	"\x0fGetGroupStudent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bdateType\x18\x03 \x01(\tR\bdateType\x12\x12\n" +
	"\x04days\x18\x04 \x03(\tR\x04days\x12&\n" +
	"\x04room\x18\x05 \x01(\v2\x12.education.AbsRoomR\x04room\x12,\n" +
	"\x06course\x18\x06 \x01(\v2\x14.education.AbsCourseR\x06course\x12(\n" +
	"\x0flessonStartTime\x18\a \x01(\tR\x0flessonStartTime\x12&\n" +
	"\x0egroupStartDate\x18\b \x01(\tR\x0egroupStartDate\x12\"\n" +
	"\fgroupEndDate\x18\t \x01(\tR\fgroupEndDate\x12*\n" +
	"\x10studentCondition\x18\v \x01(\tR\x10studentCondition\x12.\n" +
	"\x12studentActivatedAt\x18\f \x01(\tR\x12studentActivatedAt\x12&\n" +
	"\x0estudentAddedAt\x18\x0e \x01(\tR\x0estudentAddedAt\x12 \n" +
	"\vteacherName\x18\x0f \x01(\tR\vteacherName\x12(\n" +
	"\x0fpriceForStudent\x18\r \x01(\x01R\x0fpriceForStudent\"0\n" +
	"\x10StudentIdRequest\x12\x1c\n" +
	"\tstudentId\x18\x01 \x01(\tR\tstudentId\"|\n" +
	"\x1aGetGroupsByStudentResponse\x121\n" +
	"\bcomments\x18\x01 \x03(\v2\x15.common.DebtorCommentR\bcomments\x12+\n" +
	"\x06groups\x18\x02 \x03(\v2\x13.common.DebtorGroupR\x06groups\"%\n" +
	"\x13GetGroupByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xed\x02\n" +
	"\x13GetGroupAbsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vteacherName\x18\x03 \x01(\tR\vteacherName\x12\x1c\n" +
	"\tteacherId\x18\x0e \x01(\tR\tteacherId\x12(\n" +
	"\x0flessonStartTime\x18\x04 \x01(\tR\x0flessonStartTime\x12\"\n" +
	"\fstudentCount\x18\x06 \x01(\x05R\fstudentCount\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"isArchived\x18\b \x01(\bR\n" +
	"isArchived\x12\x1c\n" +
	"\tcreatedAt\x18\t \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tstartDate\x18\n" +
	" \x01(\tR\tstartDate\x12\x18\n" +
	"\aendDate\x18\v \x01(\tR\aendDate\x12\x12\n" +
	"\x04days\x18\f \x03(\tR\x04days\x12\x1a\n" +
	"\bdateType\x18\r \x01(\tR\bdateType2\x84\x04\n" +
	"\x0eStudentService\x12W\n" +
	"\x0eGetStudentById\x12\".education.NoteStudentByAbsRequest\x1a!.education.GetStudentByIdResponse\x12g\n" +
	"\x14GetStudentsByGroupId\x12&.education.GetStudentsByGroupIdRequest\x1a'.education.GetStudentsByGroupIdResponse\x12[\n" +
	"\x18ChangeUserBalanceHistory\x12*.education.ChangeUserBalanceHistoryRequest\x1a\x13.common.AbsResponse\x12i\n" +
	"\x1fChangeUserBalanceHistoryByDebit\x121.education.ChangeUserBalanceHistoryByDebitRequest\x1a\x13.common.AbsResponse\x12h\n" +
	"\x16CalculateDiscountSumma\x12(.education.CalculateDiscountSummaRequest\x1a$.education.CalculateDiscountResponse2\xba\x01\n" +
	"\fGroupService\x12N\n" +
	"\fGetGroupById\x12\x1e.education.GetGroupByIdRequest\x1a\x1e.education.GetGroupAbsResponse\x12Z\n" +
	"\x14GetGroupsByStudentId\x12\x1b.education.StudentIdRequest\x1a%.education.GetGroupsByStudentResponseB\n" +
	"Z\bproto/pbb\x06proto3"

var (
	file_education_proto_rawDescOnce sync.Once
	file_education_proto_rawDescData []byte
)

func file_education_proto_rawDescGZIP() []byte {
	file_education_proto_rawDescOnce.Do(func() {
		file_education_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_education_proto_rawDesc), len(file_education_proto_rawDesc)))
	})
	return file_education_proto_rawDescData
}

var file_education_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_education_proto_goTypes = []any{
	(*AbsRoom)(nil),                                // 0: education.AbsRoom
	(*AbsCourse)(nil),                              // 1: education.AbsCourse
	(*CalculateDiscountSummaRequest)(nil),          // 2: education.CalculateDiscountSummaRequest
	(*CalculateDiscountResponse)(nil),              // 3: education.CalculateDiscountResponse
	(*ChangeUserBalanceHistoryByDebitRequest)(nil), // 4: education.ChangeUserBalanceHistoryByDebitRequest
	(*ChangeUserBalanceHistoryRequest)(nil),        // 5: education.ChangeUserBalanceHistoryRequest
	(*GetStudentsByGroupIdResponse)(nil),           // 6: education.GetStudentsByGroupIdResponse
	(*GetStudentsByGroupIdRequest)(nil),            // 7: education.GetStudentsByGroupIdRequest
	(*AbsStudent)(nil),                             // 8: education.AbsStudent
	(*GetStudentByIdResponse)(nil),                 // 9: education.GetStudentByIdResponse
	(*NoteStudentByAbsRequest)(nil),                // 10: education.NoteStudentByAbsRequest
	(*GetGroupStudent)(nil),                        // 11: education.GetGroupStudent
	(*StudentIdRequest)(nil),                       // 12: education.StudentIdRequest
	(*GetGroupsByStudentResponse)(nil),             // 13: education.GetGroupsByStudentResponse
	(*GetGroupByIdRequest)(nil),                    // 14: education.GetGroupByIdRequest
	(*GetGroupAbsResponse)(nil),                    // 15: education.GetGroupAbsResponse
	(*DebtorComment)(nil),                          // 16: common.DebtorComment
	(*DebtorGroup)(nil),                            // 17: common.DebtorGroup
	(*AbsResponse)(nil),                            // 18: common.AbsResponse
}
var file_education_proto_depIdxs = []int32{
	8,  // 0: education.GetStudentsByGroupIdResponse.students:type_name -> education.AbsStudent
	11, // 1: education.GetStudentByIdResponse.groups:type_name -> education.GetGroupStudent
	0,  // 2: education.GetGroupStudent.room:type_name -> education.AbsRoom
	1,  // 3: education.GetGroupStudent.course:type_name -> education.AbsCourse
	16, // 4: education.GetGroupsByStudentResponse.comments:type_name -> common.DebtorComment
	17, // 5: education.GetGroupsByStudentResponse.groups:type_name -> common.DebtorGroup
	10, // 6: education.StudentService.GetStudentById:input_type -> education.NoteStudentByAbsRequest
	7,  // 7: education.StudentService.GetStudentsByGroupId:input_type -> education.GetStudentsByGroupIdRequest
	5,  // 8: education.StudentService.ChangeUserBalanceHistory:input_type -> education.ChangeUserBalanceHistoryRequest
	4,  // 9: education.StudentService.ChangeUserBalanceHistoryByDebit:input_type -> education.ChangeUserBalanceHistoryByDebitRequest
	2,  // 10: education.StudentService.CalculateDiscountSumma:input_type -> education.CalculateDiscountSummaRequest
	14, // 11: education.GroupService.GetGroupById:input_type -> education.GetGroupByIdRequest
	12, // 12: education.GroupService.GetGroupsByStudentId:input_type -> education.StudentIdRequest
	9,  // 13: education.StudentService.GetStudentById:output_type -> education.GetStudentByIdResponse
	6,  // 14: education.StudentService.GetStudentsByGroupId:output_type -> education.GetStudentsByGroupIdResponse
	18, // 15: education.StudentService.ChangeUserBalanceHistory:output_type -> common.AbsResponse
	18, // 16: education.StudentService.ChangeUserBalanceHistoryByDebit:output_type -> common.AbsResponse
	3,  // 17: education.StudentService.CalculateDiscountSumma:output_type -> education.CalculateDiscountResponse
	15, // 18: education.GroupService.GetGroupById:output_type -> education.GetGroupAbsResponse
	13, // 19: education.GroupService.GetGroupsByStudentId:output_type -> education.GetGroupsByStudentResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_education_proto_init() }
func file_education_proto_init() {
	if File_education_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_education_proto_rawDesc), len(file_education_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_education_proto_goTypes,
		DependencyIndexes: file_education_proto_depIdxs,
		MessageInfos:      file_education_proto_msgTypes,
	}.Build()
	File_education_proto = out.File
	file_education_proto_goTypes = nil
	file_education_proto_depIdxs = nil
}
