// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: lead.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetActiveLeadCountResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActiveLeadCount int32                  `protobuf:"varint,1,opt,name=activeLeadCount,proto3" json:"activeLeadCount"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetActiveLeadCountResponse) Reset() {
	*x = GetActiveLeadCountResponse{}
	mi := &file_lead_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveLeadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveLeadCountResponse) ProtoMessage() {}

func (x *GetActiveLeadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveLeadCountResponse.ProtoReflect.Descriptor instead.
func (*GetActiveLeadCountResponse) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{0}
}

func (x *GetActiveLeadCountResponse) GetActiveLeadCount() int32 {
	if x != nil {
		return x.ActiveLeadCount
	}
	return 0
}

type GetLeadReportsResponse struct {
	state                   protoimpl.MessageState     `protogen:"open.v1"`
	LeadConversion          []*LeadConversion          `protobuf:"bytes,1,rep,name=leadConversion,proto3" json:"leadConversion"`
	LeadConversionForSource []*LeadConversionForSource `protobuf:"bytes,2,rep,name=leadConversionForSource,proto3" json:"leadConversionForSource"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetLeadReportsResponse) Reset() {
	*x = GetLeadReportsResponse{}
	mi := &file_lead_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeadReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeadReportsResponse) ProtoMessage() {}

func (x *GetLeadReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeadReportsResponse.ProtoReflect.Descriptor instead.
func (*GetLeadReportsResponse) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{1}
}

func (x *GetLeadReportsResponse) GetLeadConversion() []*LeadConversion {
	if x != nil {
		return x.LeadConversion
	}
	return nil
}

func (x *GetLeadReportsResponse) GetLeadConversionForSource() []*LeadConversionForSource {
	if x != nil {
		return x.LeadConversionForSource
	}
	return nil
}

type LeadConversion struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversionDate string                 `protobuf:"bytes,1,opt,name=conversionDate,proto3" json:"conversionDate"`
	LeadCount      int32                  `protobuf:"varint,2,opt,name=lead_count,json=leadCount,proto3" json:"lead_count"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LeadConversion) Reset() {
	*x = LeadConversion{}
	mi := &file_lead_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeadConversion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadConversion) ProtoMessage() {}

func (x *LeadConversion) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeadConversion.ProtoReflect.Descriptor instead.
func (*LeadConversion) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{2}
}

func (x *LeadConversion) GetConversionDate() string {
	if x != nil {
		return x.ConversionDate
	}
	return ""
}

func (x *LeadConversion) GetLeadCount() int32 {
	if x != nil {
		return x.LeadCount
	}
	return 0
}

type LeadConversionForSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source"`
	LeadsCount    int32                  `protobuf:"varint,2,opt,name=leads_count,json=leadsCount,proto3" json:"leads_count"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeadConversionForSource) Reset() {
	*x = LeadConversionForSource{}
	mi := &file_lead_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeadConversionForSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadConversionForSource) ProtoMessage() {}

func (x *LeadConversionForSource) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeadConversionForSource.ProtoReflect.Descriptor instead.
func (*LeadConversionForSource) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{3}
}

func (x *LeadConversionForSource) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LeadConversionForSource) GetLeadsCount() int32 {
	if x != nil {
		return x.LeadsCount
	}
	return 0
}

type GetLeadReportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartYear     string                 `protobuf:"bytes,1,opt,name=startYear,proto3" json:"startYear"`
	EndYear       string                 `protobuf:"bytes,2,opt,name=endYear,proto3" json:"endYear"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeadReportsRequest) Reset() {
	*x = GetLeadReportsRequest{}
	mi := &file_lead_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeadReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeadReportsRequest) ProtoMessage() {}

func (x *GetLeadReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeadReportsRequest.ProtoReflect.Descriptor instead.
func (*GetLeadReportsRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{4}
}

func (x *GetLeadReportsRequest) GetStartYear() string {
	if x != nil {
		return x.StartYear
	}
	return ""
}

func (x *GetLeadReportsRequest) GetEndYear() string {
	if x != nil {
		return x.EndYear
	}
	return ""
}

type CreateLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLeadRequest) Reset() {
	*x = CreateLeadRequest{}
	mi := &file_lead_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLeadRequest) ProtoMessage() {}

func (x *CreateLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLeadRequest.ProtoReflect.Descriptor instead.
func (*CreateLeadRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{5}
}

func (x *CreateLeadRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GetLeadCommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leads         []*Section             `protobuf:"bytes,1,rep,name=leads,proto3" json:"leads"`
	Expectations  []*Section             `protobuf:"bytes,2,rep,name=expectations,proto3" json:"expectations"`
	Sets          []*Section             `protobuf:"bytes,3,rep,name=sets,proto3" json:"sets"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeadCommonResponse) Reset() {
	*x = GetLeadCommonResponse{}
	mi := &file_lead_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeadCommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeadCommonResponse) ProtoMessage() {}

func (x *GetLeadCommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeadCommonResponse.ProtoReflect.Descriptor instead.
func (*GetLeadCommonResponse) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{6}
}

func (x *GetLeadCommonResponse) GetLeads() []*Section {
	if x != nil {
		return x.Leads
	}
	return nil
}

func (x *GetLeadCommonResponse) GetExpectations() []*Section {
	if x != nil {
		return x.Expectations
	}
	return nil
}

func (x *GetLeadCommonResponse) GetSets() []*Section {
	if x != nil {
		return x.Sets
	}
	return nil
}

type GetLeadCommonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*LeadCommonRequest   `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeadCommonRequest) Reset() {
	*x = GetLeadCommonRequest{}
	mi := &file_lead_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeadCommonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeadCommonRequest) ProtoMessage() {}

func (x *GetLeadCommonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeadCommonRequest.ProtoReflect.Descriptor instead.
func (*GetLeadCommonRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{7}
}

func (x *GetLeadCommonRequest) GetRequests() []*LeadCommonRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type LeadCommonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeadCommonRequest) Reset() {
	*x = LeadCommonRequest{}
	mi := &file_lead_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeadCommonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadCommonRequest) ProtoMessage() {}

func (x *LeadCommonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeadCommonRequest.ProtoReflect.Descriptor instead.
func (*LeadCommonRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{8}
}

func (x *LeadCommonRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LeadCommonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Section struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	LeadsCount    int32                  `protobuf:"varint,2,opt,name=leadsCount,proto3" json:"leadsCount"`
	Leads         []*Lead                `protobuf:"bytes,3,rep,name=leads,proto3" json:"leads"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Section) Reset() {
	*x = Section{}
	mi := &file_lead_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Section) ProtoMessage() {}

func (x *Section) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Section.ProtoReflect.Descriptor instead.
func (*Section) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{9}
}

func (x *Section) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Section) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Section) GetLeadsCount() int32 {
	if x != nil {
		return x.LeadsCount
	}
	return 0
}

func (x *Section) GetLeads() []*Lead {
	if x != nil {
		return x.Leads
	}
	return nil
}

func (x *Section) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Lead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phoneNumber,proto3" json:"phoneNumber"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lead) Reset() {
	*x = Lead{}
	mi := &file_lead_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lead) ProtoMessage() {}

func (x *Lead) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lead.ProtoReflect.Descriptor instead.
func (*Lead) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{10}
}

func (x *Lead) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lead) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Lead) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Lead) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Lead) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type UpdateLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLeadRequest) Reset() {
	*x = UpdateLeadRequest{}
	mi := &file_lead_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLeadRequest) ProtoMessage() {}

func (x *UpdateLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLeadRequest.ProtoReflect.Descriptor instead.
func (*UpdateLeadRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateLeadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLeadRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GetLeadListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sections      []*DynamicSection      `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeadListResponse) Reset() {
	*x = GetLeadListResponse{}
	mi := &file_lead_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeadListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeadListResponse) ProtoMessage() {}

func (x *GetLeadListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeadListResponse.ProtoReflect.Descriptor instead.
func (*GetLeadListResponse) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{12}
}

func (x *GetLeadListResponse) GetSections() []*DynamicSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

type DynamicSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicSection) Reset() {
	*x = DynamicSection{}
	mi := &file_lead_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicSection) ProtoMessage() {}

func (x *DynamicSection) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicSection.ProtoReflect.Descriptor instead.
func (*DynamicSection) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{13}
}

func (x *DynamicSection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DynamicSection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateExpectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExpectRequest) Reset() {
	*x = CreateExpectRequest{}
	mi := &file_lead_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpectRequest) ProtoMessage() {}

func (x *CreateExpectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpectRequest.ProtoReflect.Descriptor instead.
func (*CreateExpectRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{14}
}

func (x *CreateExpectRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type UpdateExpectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExpectRequest) Reset() {
	*x = UpdateExpectRequest{}
	mi := &file_lead_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExpectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExpectRequest) ProtoMessage() {}

func (x *UpdateExpectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExpectRequest.ProtoReflect.Descriptor instead.
func (*UpdateExpectRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateExpectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateExpectRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateSetRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title"`
	CourseId        string                 `protobuf:"bytes,2,opt,name=courseId,proto3" json:"courseId"`
	TeacherId       string                 `protobuf:"bytes,3,opt,name=teacherId,proto3" json:"teacherId"`
	DateType        string                 `protobuf:"bytes,4,opt,name=dateType,proto3" json:"dateType"`
	Date            []string               `protobuf:"bytes,5,rep,name=date,proto3" json:"date"`
	LessonStartTime string                 `protobuf:"bytes,6,opt,name=lessonStartTime,proto3" json:"lessonStartTime"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateSetRequest) Reset() {
	*x = CreateSetRequest{}
	mi := &file_lead_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSetRequest) ProtoMessage() {}

func (x *CreateSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSetRequest.ProtoReflect.Descriptor instead.
func (*CreateSetRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{16}
}

func (x *CreateSetRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSetRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CreateSetRequest) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *CreateSetRequest) GetDateType() string {
	if x != nil {
		return x.DateType
	}
	return ""
}

func (x *CreateSetRequest) GetDate() []string {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *CreateSetRequest) GetLessonStartTime() string {
	if x != nil {
		return x.LessonStartTime
	}
	return ""
}

type UpdateSetRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,7,opt,name=id,proto3" json:"id"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title"`
	CourseId        string                 `protobuf:"bytes,2,opt,name=courseId,proto3" json:"courseId"`
	TeacherId       string                 `protobuf:"bytes,3,opt,name=teacherId,proto3" json:"teacherId"`
	DateType        string                 `protobuf:"bytes,4,opt,name=dateType,proto3" json:"dateType"`
	Date            []string               `protobuf:"bytes,5,rep,name=date,proto3" json:"date"`
	LessonStartTime string                 `protobuf:"bytes,6,opt,name=lessonStartTime,proto3" json:"lessonStartTime"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateSetRequest) Reset() {
	*x = UpdateSetRequest{}
	mi := &file_lead_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSetRequest) ProtoMessage() {}

func (x *UpdateSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSetRequest.ProtoReflect.Descriptor instead.
func (*UpdateSetRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateSetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSetRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateSetRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *UpdateSetRequest) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *UpdateSetRequest) GetDateType() string {
	if x != nil {
		return x.DateType
	}
	return ""
}

func (x *UpdateSetRequest) GetDate() []string {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *UpdateSetRequest) GetLessonStartTime() string {
	if x != nil {
		return x.LessonStartTime
	}
	return ""
}

type SetDataResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title"`
	TeacherId       string                 `protobuf:"bytes,2,opt,name=teacherId,proto3" json:"teacherId"`
	TeacherName     string                 `protobuf:"bytes,3,opt,name=teacherName,proto3" json:"teacherName"`
	CourseId        string                 `protobuf:"bytes,4,opt,name=courseId,proto3" json:"courseId"`
	CourseName      string                 `protobuf:"bytes,5,opt,name=courseName,proto3" json:"courseName"`
	DateType        string                 `protobuf:"bytes,6,opt,name=dateType,proto3" json:"dateType"`
	Dates           []string               `protobuf:"bytes,7,rep,name=dates,proto3" json:"dates"`
	LessonStartTime string                 `protobuf:"bytes,8,opt,name=lessonStartTime,proto3" json:"lessonStartTime"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetDataResponse) Reset() {
	*x = SetDataResponse{}
	mi := &file_lead_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDataResponse) ProtoMessage() {}

func (x *SetDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDataResponse.ProtoReflect.Descriptor instead.
func (*SetDataResponse) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{18}
}

func (x *SetDataResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SetDataResponse) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *SetDataResponse) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

func (x *SetDataResponse) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *SetDataResponse) GetCourseName() string {
	if x != nil {
		return x.CourseName
	}
	return ""
}

func (x *SetDataResponse) GetDateType() string {
	if x != nil {
		return x.DateType
	}
	return ""
}

func (x *SetDataResponse) GetDates() []string {
	if x != nil {
		return x.Dates
	}
	return nil
}

func (x *SetDataResponse) GetLessonStartTime() string {
	if x != nil {
		return x.LessonStartTime
	}
	return ""
}

type ChangeToSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId"`
	CourseId      string                 `protobuf:"bytes,3,opt,name=courseId,proto3" json:"courseId"`
	TeacherId     string                 `protobuf:"bytes,4,opt,name=teacherId,proto3" json:"teacherId"`
	DateType      string                 `protobuf:"bytes,5,opt,name=dateType,proto3" json:"dateType"`
	Days          []string               `protobuf:"bytes,6,rep,name=days,proto3" json:"days"`
	StartTime     string                 `protobuf:"bytes,7,opt,name=startTime,proto3" json:"startTime"`
	StartDate     string                 `protobuf:"bytes,8,opt,name=startDate,proto3" json:"startDate"`
	EndDate       string                 `protobuf:"bytes,9,opt,name=end_date,json=endDate,proto3" json:"end_date"`
	SetId         string                 `protobuf:"bytes,10,opt,name=setId,proto3" json:"setId"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeToSetRequest) Reset() {
	*x = ChangeToSetRequest{}
	mi := &file_lead_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeToSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeToSetRequest) ProtoMessage() {}

func (x *ChangeToSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeToSetRequest.ProtoReflect.Descriptor instead.
func (*ChangeToSetRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{19}
}

func (x *ChangeToSetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChangeToSetRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ChangeToSetRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *ChangeToSetRequest) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *ChangeToSetRequest) GetDateType() string {
	if x != nil {
		return x.DateType
	}
	return ""
}

func (x *ChangeToSetRequest) GetDays() []string {
	if x != nil {
		return x.Days
	}
	return nil
}

func (x *ChangeToSetRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ChangeToSetRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ChangeToSetRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *ChangeToSetRequest) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

type CreateLeadDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=phoneNumber,proto3" json:"phoneNumber"`
	LeadId        string                 `protobuf:"bytes,3,opt,name=leadId,proto3" json:"leadId"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLeadDataRequest) Reset() {
	*x = CreateLeadDataRequest{}
	mi := &file_lead_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLeadDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLeadDataRequest) ProtoMessage() {}

func (x *CreateLeadDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLeadDataRequest.ProtoReflect.Descriptor instead.
func (*CreateLeadDataRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{20}
}

func (x *CreateLeadDataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateLeadDataRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateLeadDataRequest) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

func (x *CreateLeadDataRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type UpdateLeadDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type"`
	SectionId     string                 `protobuf:"bytes,6,opt,name=sectionId,proto3" json:"sectionId"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=phoneNumber,proto3" json:"phoneNumber"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLeadDataRequest) Reset() {
	*x = UpdateLeadDataRequest{}
	mi := &file_lead_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLeadDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLeadDataRequest) ProtoMessage() {}

func (x *UpdateLeadDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLeadDataRequest.ProtoReflect.Descriptor instead.
func (*UpdateLeadDataRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateLeadDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLeadDataRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateLeadDataRequest) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

func (x *UpdateLeadDataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateLeadDataRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UpdateLeadDataRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type ChangeLeadPlaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeadDataId    string                 `protobuf:"bytes,1,opt,name=leadDataId,proto3" json:"leadDataId"`
	ChangedSet    *ChangeLeadDataRequest `protobuf:"bytes,2,opt,name=changedSet,proto3" json:"changedSet"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeLeadPlaceRequest) Reset() {
	*x = ChangeLeadPlaceRequest{}
	mi := &file_lead_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeLeadPlaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeLeadPlaceRequest) ProtoMessage() {}

func (x *ChangeLeadPlaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeLeadPlaceRequest.ProtoReflect.Descriptor instead.
func (*ChangeLeadPlaceRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{22}
}

func (x *ChangeLeadPlaceRequest) GetLeadDataId() string {
	if x != nil {
		return x.LeadDataId
	}
	return ""
}

func (x *ChangeLeadPlaceRequest) GetChangedSet() *ChangeLeadDataRequest {
	if x != nil {
		return x.ChangedSet
	}
	return nil
}

type ChangeLeadDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	SectionType   string                 `protobuf:"bytes,2,opt,name=sectionType,proto3" json:"sectionType"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeLeadDataRequest) Reset() {
	*x = ChangeLeadDataRequest{}
	mi := &file_lead_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeLeadDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeLeadDataRequest) ProtoMessage() {}

func (x *ChangeLeadDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeLeadDataRequest.ProtoReflect.Descriptor instead.
func (*ChangeLeadDataRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{23}
}

func (x *ChangeLeadDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeLeadDataRequest) GetSectionType() string {
	if x != nil {
		return x.SectionType
	}
	return ""
}

var File_lead_proto protoreflect.FileDescriptor

const file_lead_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"lead.proto\x12\x04lead\x1a\fcommon.proto\x1a\x1bgoogle/protobuf/empty.proto\"F\n" +
	"\x1aGetActiveLeadCountResponse\x12(\n" +
	"\x0factiveLeadCount\x18\x01 \x01(\x05R\x0factiveLeadCount\"\xaf\x01\n" +
	"\x16GetLeadReportsResponse\x12<\n" +
	"\x0eleadConversion\x18\x01 \x03(\v2\x14.lead.LeadConversionR\x0eleadConversion\x12W\n" +
	"\x17leadConversionForSource\x18\x02 \x03(\v2\x1d.lead.LeadConversionForSourceR\x17leadConversionForSource\"W\n" +
	"\x0eLeadConversion\x12&\n" +
	"\x0econversionDate\x18\x01 \x01(\tR\x0econversionDate\x12\x1d\n" +
	"\n" +
	"lead_count\x18\x02 \x01(\x05R\tleadCount\"R\n" +
	"\x17LeadConversionForSource\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1f\n" +
	"\vleads_count\x18\x02 \x01(\x05R\n" +
	"leadsCount\"O\n" +
	"\x15GetLeadReportsRequest\x12\x1c\n" +
	"\tstartYear\x18\x01 \x01(\tR\tstartYear\x12\x18\n" +
	"\aendYear\x18\x02 \x01(\tR\aendYear\")\n" +
	"\x11CreateLeadRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"\x92\x01\n" +
	"\x15GetLeadCommonResponse\x12#\n" +
	"\x05leads\x18\x01 \x03(\v2\r.lead.SectionR\x05leads\x121\n" +
	"\fexpectations\x18\x02 \x03(\v2\r.lead.SectionR\fexpectations\x12!\n" +
	"\x04sets\x18\x03 \x03(\v2\r.lead.SectionR\x04sets\"K\n" +
	"\x14GetLeadCommonRequest\x123\n" +
	"\brequests\x18\x01 \x03(\v2\x17.lead.LeadCommonRequestR\brequests\"7\n" +
	"\x11LeadCommonRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x83\x01\n" +
	"\aSection\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"leadsCount\x18\x02 \x01(\x05R\n" +
	"leadsCount\x12 \n" +
	"\x05leads\x18\x03 \x03(\v2\n" +
	".lead.LeadR\x05leads\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"\x84\x01\n" +
	"\x04Lead\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12\x1c\n" +
	"\tcreatedAt\x18\x03 \x01(\tR\tcreatedAt\x12 \n" +
	"\vphoneNumber\x18\x04 \x01(\tR\vphoneNumber\"9\n" +
	"\x11UpdateLeadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"G\n" +
	"\x13GetLeadListResponse\x120\n" +
	"\bsections\x18\x01 \x03(\v2\x14.lead.DynamicSectionR\bsections\"4\n" +
	"\x0eDynamicSection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"+\n" +
	"\x13CreateExpectRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\";\n" +
	"\x13UpdateExpectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"\xbc\x01\n" +
	"\x10CreateSetRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1a\n" +
	"\bcourseId\x18\x02 \x01(\tR\bcourseId\x12\x1c\n" +
	"\tteacherId\x18\x03 \x01(\tR\tteacherId\x12\x1a\n" +
	"\bdateType\x18\x04 \x01(\tR\bdateType\x12\x12\n" +
	"\x04date\x18\x05 \x03(\tR\x04date\x12(\n" +
	"\x0flessonStartTime\x18\x06 \x01(\tR\x0flessonStartTime\"\xcc\x01\n" +
	"\x10UpdateSetRequest\x12\x0e\n" +
	"\x02id\x18\a \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1a\n" +
	"\bcourseId\x18\x02 \x01(\tR\bcourseId\x12\x1c\n" +
	"\tteacherId\x18\x03 \x01(\tR\tteacherId\x12\x1a\n" +
	"\bdateType\x18\x04 \x01(\tR\bdateType\x12\x12\n" +
	"\x04date\x18\x05 \x03(\tR\x04date\x12(\n" +
	"\x0flessonStartTime\x18\x06 \x01(\tR\x0flessonStartTime\"\xff\x01\n" +
	"\x0fSetDataResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1c\n" +
	"\tteacherId\x18\x02 \x01(\tR\tteacherId\x12 \n" +
	"\vteacherName\x18\x03 \x01(\tR\vteacherName\x12\x1a\n" +
	"\bcourseId\x18\x04 \x01(\tR\bcourseId\x12\x1e\n" +
	"\n" +
	"courseName\x18\x05 \x01(\tR\n" +
	"courseName\x12\x1a\n" +
	"\bdateType\x18\x06 \x01(\tR\bdateType\x12\x14\n" +
	"\x05dates\x18\a \x03(\tR\x05dates\x12(\n" +
	"\x0flessonStartTime\x18\b \x01(\tR\x0flessonStartTime\"\x97\x02\n" +
	"\x12ChangeToSetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06roomId\x18\x02 \x01(\tR\x06roomId\x12\x1a\n" +
	"\bcourseId\x18\x03 \x01(\tR\bcourseId\x12\x1c\n" +
	"\tteacherId\x18\x04 \x01(\tR\tteacherId\x12\x1a\n" +
	"\bdateType\x18\x05 \x01(\tR\bdateType\x12\x12\n" +
	"\x04days\x18\x06 \x03(\tR\x04days\x12\x1c\n" +
	"\tstartTime\x18\a \x01(\tR\tstartTime\x12\x1c\n" +
	"\tstartDate\x18\b \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\t \x01(\tR\aendDate\x12\x14\n" +
	"\x05setId\x18\n" +
	" \x01(\tR\x05setId\"\x7f\n" +
	"\x15CreateLeadDataRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vphoneNumber\x18\x02 \x01(\tR\vphoneNumber\x12\x16\n" +
	"\x06leadId\x18\x03 \x01(\tR\x06leadId\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"\xa9\x01\n" +
	"\x15UpdateLeadDataRequest\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1c\n" +
	"\tsectionId\x18\x06 \x01(\tR\tsectionId\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vphoneNumber\x18\x02 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"u\n" +
	"\x16ChangeLeadPlaceRequest\x12\x1e\n" +
	"\n" +
	"leadDataId\x18\x01 \x01(\tR\n" +
	"leadDataId\x12;\n" +
	"\n" +
	"changedSet\x18\x02 \x01(\v2\x1b.lead.ChangeLeadDataRequestR\n" +
	"changedSet\"I\n" +
	"\x15ChangeLeadDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vsectionType\x18\x02 \x01(\tR\vsectionType2\xee\x03\n" +
	"\vLeadService\x12:\n" +
	"\n" +
	"CreateLead\x12\x17.lead.CreateLeadRequest\x1a\x13.common.AbsResponse\x12H\n" +
	"\rGetLeadCommon\x12\x1a.lead.GetLeadCommonRequest\x1a\x1b.lead.GetLeadCommonResponse\x12:\n" +
	"\n" +
	"UpdateLead\x12\x17.lead.UpdateLeadRequest\x1a\x13.common.AbsResponse\x12;\n" +
	"\n" +
	"DeleteLead\x12\x18.common.DeleteAbsRequest\x1a\x13.common.AbsResponse\x12C\n" +
	"\x0eGetListSection\x12\x16.google.protobuf.Empty\x1a\x19.lead.GetLeadListResponse\x12K\n" +
	"\x0eGetLeadReports\x12\x1b.lead.GetLeadReportsRequest\x1a\x1c.lead.GetLeadReportsResponse\x12N\n" +
	"\x12GetActiveLeadCount\x12\x16.google.protobuf.Empty\x1a .lead.GetActiveLeadCountResponse2\xce\x01\n" +
	"\rExpectService\x12>\n" +
	"\fCreateExpect\x12\x19.lead.CreateExpectRequest\x1a\x13.common.AbsResponse\x12>\n" +
	"\fUpdateExpect\x12\x19.lead.UpdateExpectRequest\x1a\x13.common.AbsResponse\x12=\n" +
	"\fDeleteExpect\x12\x18.common.DeleteAbsRequest\x1a\x13.common.AbsResponse2\xb6\x02\n" +
	"\n" +
	"SetService\x128\n" +
	"\tCreateSet\x12\x16.lead.CreateSetRequest\x1a\x13.common.AbsResponse\x128\n" +
	"\tUpdateSet\x12\x16.lead.UpdateSetRequest\x1a\x13.common.AbsResponse\x12:\n" +
	"\tDeleteSet\x12\x18.common.DeleteAbsRequest\x1a\x13.common.AbsResponse\x12<\n" +
	"\vChangeToSet\x12\x18.lead.ChangeToSetRequest\x1a\x13.common.AbsResponse\x12:\n" +
	"\aGetById\x12\x18.common.DeleteAbsRequest\x1a\x15.lead.SetDataResponse2\xa0\x02\n" +
	"\x0fLeadDataService\x12B\n" +
	"\x0eCreateLeadData\x12\x1b.lead.CreateLeadDataRequest\x1a\x13.common.AbsResponse\x12B\n" +
	"\x0eUpdateLeadData\x12\x1b.lead.UpdateLeadDataRequest\x1a\x13.common.AbsResponse\x12?\n" +
	"\x0eDeleteLeadData\x12\x18.common.DeleteAbsRequest\x1a\x13.common.AbsResponse\x12D\n" +
	"\x0fChangeLeadPlace\x12\x1c.lead.ChangeLeadPlaceRequest\x1a\x13.common.AbsResponseB\x0fZ\rgrpc/proto/pbb\x06proto3"

var (
	file_lead_proto_rawDescOnce sync.Once
	file_lead_proto_rawDescData []byte
)

func file_lead_proto_rawDescGZIP() []byte {
	file_lead_proto_rawDescOnce.Do(func() {
		file_lead_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lead_proto_rawDesc), len(file_lead_proto_rawDesc)))
	})
	return file_lead_proto_rawDescData
}

var file_lead_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_lead_proto_goTypes = []any{
	(*GetActiveLeadCountResponse)(nil), // 0: lead.GetActiveLeadCountResponse
	(*GetLeadReportsResponse)(nil),     // 1: lead.GetLeadReportsResponse
	(*LeadConversion)(nil),             // 2: lead.LeadConversion
	(*LeadConversionForSource)(nil),    // 3: lead.LeadConversionForSource
	(*GetLeadReportsRequest)(nil),      // 4: lead.GetLeadReportsRequest
	(*CreateLeadRequest)(nil),          // 5: lead.CreateLeadRequest
	(*GetLeadCommonResponse)(nil),      // 6: lead.GetLeadCommonResponse
	(*GetLeadCommonRequest)(nil),       // 7: lead.GetLeadCommonRequest
	(*LeadCommonRequest)(nil),          // 8: lead.LeadCommonRequest
	(*Section)(nil),                    // 9: lead.Section
	(*Lead)(nil),                       // 10: lead.Lead
	(*UpdateLeadRequest)(nil),          // 11: lead.UpdateLeadRequest
	(*GetLeadListResponse)(nil),        // 12: lead.GetLeadListResponse
	(*DynamicSection)(nil),             // 13: lead.DynamicSection
	(*CreateExpectRequest)(nil),        // 14: lead.CreateExpectRequest
	(*UpdateExpectRequest)(nil),        // 15: lead.UpdateExpectRequest
	(*CreateSetRequest)(nil),           // 16: lead.CreateSetRequest
	(*UpdateSetRequest)(nil),           // 17: lead.UpdateSetRequest
	(*SetDataResponse)(nil),            // 18: lead.SetDataResponse
	(*ChangeToSetRequest)(nil),         // 19: lead.ChangeToSetRequest
	(*CreateLeadDataRequest)(nil),      // 20: lead.CreateLeadDataRequest
	(*UpdateLeadDataRequest)(nil),      // 21: lead.UpdateLeadDataRequest
	(*ChangeLeadPlaceRequest)(nil),     // 22: lead.ChangeLeadPlaceRequest
	(*ChangeLeadDataRequest)(nil),      // 23: lead.ChangeLeadDataRequest
	(*DeleteAbsRequest)(nil),           // 24: common.DeleteAbsRequest
	(*emptypb.Empty)(nil),              // 25: google.protobuf.Empty
	(*AbsResponse)(nil),                // 26: common.AbsResponse
}
var file_lead_proto_depIdxs = []int32{
	2,  // 0: lead.GetLeadReportsResponse.leadConversion:type_name -> lead.LeadConversion
	3,  // 1: lead.GetLeadReportsResponse.leadConversionForSource:type_name -> lead.LeadConversionForSource
	9,  // 2: lead.GetLeadCommonResponse.leads:type_name -> lead.Section
	9,  // 3: lead.GetLeadCommonResponse.expectations:type_name -> lead.Section
	9,  // 4: lead.GetLeadCommonResponse.sets:type_name -> lead.Section
	8,  // 5: lead.GetLeadCommonRequest.requests:type_name -> lead.LeadCommonRequest
	10, // 6: lead.Section.leads:type_name -> lead.Lead
	13, // 7: lead.GetLeadListResponse.sections:type_name -> lead.DynamicSection
	23, // 8: lead.ChangeLeadPlaceRequest.changedSet:type_name -> lead.ChangeLeadDataRequest
	5,  // 9: lead.LeadService.CreateLead:input_type -> lead.CreateLeadRequest
	7,  // 10: lead.LeadService.GetLeadCommon:input_type -> lead.GetLeadCommonRequest
	11, // 11: lead.LeadService.UpdateLead:input_type -> lead.UpdateLeadRequest
	24, // 12: lead.LeadService.DeleteLead:input_type -> common.DeleteAbsRequest
	25, // 13: lead.LeadService.GetListSection:input_type -> google.protobuf.Empty
	4,  // 14: lead.LeadService.GetLeadReports:input_type -> lead.GetLeadReportsRequest
	25, // 15: lead.LeadService.GetActiveLeadCount:input_type -> google.protobuf.Empty
	14, // 16: lead.ExpectService.CreateExpect:input_type -> lead.CreateExpectRequest
	15, // 17: lead.ExpectService.UpdateExpect:input_type -> lead.UpdateExpectRequest
	24, // 18: lead.ExpectService.DeleteExpect:input_type -> common.DeleteAbsRequest
	16, // 19: lead.SetService.CreateSet:input_type -> lead.CreateSetRequest
	17, // 20: lead.SetService.UpdateSet:input_type -> lead.UpdateSetRequest
	24, // 21: lead.SetService.DeleteSet:input_type -> common.DeleteAbsRequest
	19, // 22: lead.SetService.ChangeToSet:input_type -> lead.ChangeToSetRequest
	24, // 23: lead.SetService.GetById:input_type -> common.DeleteAbsRequest
	20, // 24: lead.LeadDataService.CreateLeadData:input_type -> lead.CreateLeadDataRequest
	21, // 25: lead.LeadDataService.UpdateLeadData:input_type -> lead.UpdateLeadDataRequest
	24, // 26: lead.LeadDataService.DeleteLeadData:input_type -> common.DeleteAbsRequest
	22, // 27: lead.LeadDataService.ChangeLeadPlace:input_type -> lead.ChangeLeadPlaceRequest
	26, // 28: lead.LeadService.CreateLead:output_type -> common.AbsResponse
	6,  // 29: lead.LeadService.GetLeadCommon:output_type -> lead.GetLeadCommonResponse
	26, // 30: lead.LeadService.UpdateLead:output_type -> common.AbsResponse
	26, // 31: lead.LeadService.DeleteLead:output_type -> common.AbsResponse
	12, // 32: lead.LeadService.GetListSection:output_type -> lead.GetLeadListResponse
	1,  // 33: lead.LeadService.GetLeadReports:output_type -> lead.GetLeadReportsResponse
	0,  // 34: lead.LeadService.GetActiveLeadCount:output_type -> lead.GetActiveLeadCountResponse
	26, // 35: lead.ExpectService.CreateExpect:output_type -> common.AbsResponse
	26, // 36: lead.ExpectService.UpdateExpect:output_type -> common.AbsResponse
	26, // 37: lead.ExpectService.DeleteExpect:output_type -> common.AbsResponse
	26, // 38: lead.SetService.CreateSet:output_type -> common.AbsResponse
	26, // 39: lead.SetService.UpdateSet:output_type -> common.AbsResponse
	26, // 40: lead.SetService.DeleteSet:output_type -> common.AbsResponse
	26, // 41: lead.SetService.ChangeToSet:output_type -> common.AbsResponse
	18, // 42: lead.SetService.GetById:output_type -> lead.SetDataResponse
	26, // 43: lead.LeadDataService.CreateLeadData:output_type -> common.AbsResponse
	26, // 44: lead.LeadDataService.UpdateLeadData:output_type -> common.AbsResponse
	26, // 45: lead.LeadDataService.DeleteLeadData:output_type -> common.AbsResponse
	26, // 46: lead.LeadDataService.ChangeLeadPlace:output_type -> common.AbsResponse
	28, // [28:47] is the sub-list for method output_type
	9,  // [9:28] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_lead_proto_init() }
func file_lead_proto_init() {
	if File_lead_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lead_proto_rawDesc), len(file_lead_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_lead_proto_goTypes,
		DependencyIndexes: file_lead_proto_depIdxs,
		MessageInfos:      file_lead_proto_msgTypes,
	}.Build()
	File_lead_proto = out.File
	file_lead_proto_goTypes = nil
	file_lead_proto_depIdxs = nil
}
